# Install Dependencies

In [ ]:
!pip install -q --no-deps xformers trl peft accelerate bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31.5/31.5 MB 70.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 366.3/366.3 kB 24.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 MB 34.9 MB/s eta 0:00:00

In [ ]:
!pip install -q datasets
!pip install -q regex

In [ ]:
!pip install -q emoji
!pip install -q PyArabic

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.4/126.4 kB 2.5 MB/s eta 0:00:00

In [ ]:
!pip install -q diffusers

# login

In [ ]:
import huggingface_hub
huggingface_hub.login('HF_TOKEN')

# Import Required Modules

In [ ]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ['CUDA_LAUNCH_BLOCKING']="1"
os.environ['TORCH_USE_CUDA_DSA'] = "1"

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
import numpy as np
import pandas as pd
import random
from sklearn.utils import shuffle
import os
import re
from tqdm import tqdm
import bitsandbytes as bnb
import torch
import torch.nn as nn
import transformers
from datasets import Dataset
from peft import LoraConfig, PeftConfig
from trl import SFTTrainer
from transformers import (AutoModelForCausalLM,
                          AutoTokenizer,
                          BitsAndBytesConfig,
                          TrainingArguments,
                          pipeline,
                          logging)
from sklearn.metrics import (accuracy_score,
                             classification_report,
                             precision_score,
                             recall_score,
                             f1_score,
                             confusion_matrix)
from sklearn.model_selection import train_test_split
import emoji
import pyarabic.araby as araby

In [ ]:
import pandas as pd

In [ ]:
import torch
import torch.distributed as dist

# Load Model

In [ ]:
model_name = "ALLaM-AI/ALLaM-7B-Instruct-preview"

compute_dtype = getattr(torch, "float16")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=False,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    # quantization_config=bnb_config,
    device_map={"": 0},
    trust_remote_code=True,
)

model.config.use_cache = False
model.config.pretraining_tp = 1

tokenizer = AutoTokenizer.from_pretrained(model_name,
                                          trust_remote_code=True,
                                          padding_side="left",
                                          add_eos_token=True,
                                         )

# Assign pad_token if missing
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "left"

In [ ]:
pipe = pipeline(task="text-generation",
                model=model,
                tokenizer=tokenizer,
                max_new_tokens=20,
                temperature=0.2
               )

# Zero Shot

In [ ]:
import pandas as pd
data = pd.read_excel('News Classification Jais Zero Shot.xlsx')

In [ ]:
data.shape

(1000, 1)

# Predict Without Fine-tuning

In [ ]:
from tqdm import tqdm
max_length = tokenizer.model_max_length
for i in tqdm(range(len(data[:6]))):
    prompt = data.iloc[i]["prompt"]
    prompt = prompt[:max_length]
    result = pipe(prompt, pad_token_id=pipe.tokenizer.eos_token_id)
    answer = result[0]['generated_text'].split("الفئة المتوقعة:")[-1].lower()
    print('\n')
    print(result)
    print('\n')
    print(answer)

 17%|█▋        | 1/6 [00:01<00:07,  1.54s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\n محتوى المقال: \nاستقبل الوسط المسرحي الإماراتي فوز الإمارات برئاسة الهيئة الدولية للمسرح بالكثير من الزهو والسعادة، وأعرب عدد من المشتغلين في المسرح عن فرحهم بهذا الإنجاز الذي يضاف إلى الرصيد الفني المحلي الذي قام على جهود عناصر مسرحية مسكونة بالجدية والمسؤولية .وأشار المسرحيون الإماراتيون إلى الجهود المتواصلة التي بذلها زميلهم محمد سيف الأفخم محلياً وعربياً ودولياً إلى أن قطفت الإمارات هذا النجاح الذي تستحقه، وتفوّقت على ست دول ذات رصيد تاريخي في فن المسرح .وقال د . حبيب غلوم: "نبارك لمحمد الأفخم ولأنفسنا اختياره رئيساً للهيئة الدولية للمسرح، وهو ولا شك ثمرة لاجتهاد وعطاء قيم، ونتمنى أن يترجم طموح من اختاروه، وأن تخطو به الإمارات نحو الأمام، من خلال فعل مسرحي متصل ومستمر يغطي كامل السنة، لأننا اليوم نحتاج إلى عمل مسرحي يتواصل خارج المهرجانات، ويوجد في الساحة حراكا يومياً معمماً على الفرق والمدن كافة" .المسرحي سلطان النيادي قال: "الأفخم من الشباب الإماراتيين الذين كرسوا جهداً كبيراً للثقافة والمسرح، ومن عادة ابن الإمارات أن يتميز إذا كرس جهده في اتجاه معين، نحن نبارك له ولأنفسنا هذا النجاح، ونعول عليه في عطاء أكبر وزيادة واتساع في الفعل المسرحي الإماراتي، وكذلك نأمل أن يقدم بصمة دولية على مستوى الهيئة التي يرأسها" .وقال حميد سمبيج: "هذا الفوز هو ثمرة جهد بذله الأفخ والعناصر المسرحية الإماراتية، من خلال عمله ومسؤولياته، وكذلك جهد الساحة المسرحية الإماراتية ككل، تلك الساحة التي هيأت الظروف لهذا الفوز من خلال السمعة الجيدة التي أصبح يحظى بها المسرح الإماراتي، نتيجة فعل مسرحي متميز ومستمر على مدى العام كان انطلاقه من الشارقة وعم اليوم جميع ربوع البلاد حتى أصبحت الإمارات عاصمة المسرح في الوطن العربي، بل عاصمة لنشاط ثقافي له أبعاد عربية وعالمية" .وأضاف سمبيج: نحن نفخر كثيراً بهذا الفوز، ونعتبره فوزاً للإمارات عامة، وهو فوز طبيعي ومستحق، لأن محمد الأفحم عمل بجهد واجتهاد وارتقى بمهرجان الفجيرة للمونودراما إلى أن أصبح فعلاً مسرحياً عالمياً، وأنا على يقين أن هذا الفوز سيثري الهيئة الدولية للمسرح بخبرة إماراتية جديدة .الفنان عبدالله زيد قال: "النجاح وليد المثابرة، ولن يصل إلى القمة من ظل قابعا في السفح، ومحمد الأفخم مثابر ومجتهد، وكل الوسط المسرحي الإماراتي مثابر ومجتهد، وهو مثال للشاب الإماراتي المفعم بالعطاء والحماسة للعمل، وليس غريباً على أبناء الإمارات الفوز واستحقاق المناصب العالية، نحن فخورون بأن يفوز أحد رجالنا المتميزين، وأن تتربع الإمارات على رئاسة هذه الهيئة المسرحية الدولية" .وقال د . هيثم الخواجه: "الحراك المسرحي في دولة الإمارات العربية المتحدة الذي بدأ منذ عقدين تقريباً حقق الكثير من النجاحات، سواء فيما يتعلق بكتابة النص المسرحي أو العرض المسرحي أو ما يمهد لذلك من ورش ومختبرات ومهرجانات، والذي جعل الحراك المسرحي متميزاً أيضاً هو البدء من المسرح المدرسي إلى مسرح الأطفال إلى الجامعي إلى الشباب إلى مسرح الكبار، هذه البنية المتكاملة جعلت الحركة المسرحية في الإمارات قابلة للتطور والنمو ما حقق الفوز في كثيرمن العروض والجوائز الكبيرة، ولا ريب أن صاحب السمو الشيخ الدكتور سلطان بن محمد القاسمي عضو المجلس الأعلى حاكم الشارقة، الذي قدم دعماً مادياً ومعنوياً وإبداعياً للمسرح أضاف الكثير إلى هذا الفن العظيم" .وأضاف الخواجة: كل ذلك أهّل الحركة المسرحية في الإمارات لأن تكون مضيئة بشكل حقيقي، وما رأيناه أن هذا الفوز جاء بشكل حقيقي، وما أراه أن هذا الفوز تستحقه دولة الإمارات بجدارة، طالما أن ما يحيط بها لم يصل إلى هذا المستوى من العطاء .\n الفئة المتوقعة: \nالفئة المتوقعة: \nالثقافة '}]



الثقافة

 33%|███▎      | 2/6 [00:02<00:04,  1.18s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\n محتوى المقال: \nاستضاف مركز الشارقة لفن الخط العربي والزخرفة مساء أمس الأول معرض ( حرف ولون ) لأعمال منتسبي المركز التابع لمجمع الشارقة للآداب والفنون، بحضور هنا سيف السويدي رئيسة هيئة البيئة والمحميات الطبيعية وعضو المجلس التنفيذي، وهشام المظلوم رئيس المجمع.شارك في المعرض أربعون منتسباً للمركز، وبلغ عدد الأعمال 50 عملاً خطياً وفق خطوط وزخارف متنوعة ومختلفة في المدارس والاتجاهات، وتبدو في المعرض الذي يضم مجموعة من اللوحات الخطية قضية تأكيد الابتكار جلية بالرغم من الالتزام الواضح بميزان القواعد ونواظم كل نوع من الخطوط المستهدفة للتعبير عن التراكيب البصرية اللافتة للخط العربي الأصيل، ولوحظ أن المواضيع المطروحة متعددة بدءاً من الآيات الكريمة وانتهاء بتشكيل مجرد للأحرف، إلا أن اللون كما هو واضح في عنوان المعرض كان حاضراً في كثير من اللوحات في خطوة للتفرد ولتنويع الإيقاع، وكان لخط النسخ والديواني الجلي حضور واسع ومهم بين الخطوط والمعروضات. رافق المعرض ورشة «خط» أشرفت عليها مروة منذر، وطلال السباعي، وشارك فيها مجموعة من الحضور، حيث شاهدوا تطبيقاً عملياً لكتابة بعض العبارات والأسماء.\n الفئة المتوقعة: \nالفئة المتوقعة: الثقافة '}]


 الثقافة

 50%|█████     | 3/6 [00:03<00:03,  1.26s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\n محتوى المقال: \nباسمة يونس قد يبدو العنوان اسماً لرواية؛ لكنه الاسم الذي أطلقته جامعة كيس ويسترن ريزرف في ولاية كليفلاند على معهد أسسته عام 2001؛ للتوعية بأهمية الحب، الذي لا يحده شيء من خلال البحث في معنى هذا الحب، وكل عناصره المحيطة به. وتعرف هذه المؤسسة الحب في رسالتها على أنه الشعور الداخلي الذي يجعل من سعادة شخص آخر وطمأنينته واستقراره دافعاً للشعور بالسعادة، بما يعني أن من يسعد لسعادة شخص آخر فهو يحبه حباً حقيقياً ومطلقاً.وقد تأسست فكرة المعهد على قانون بسيط مفاده، أن الحب اللامحدود يقوم على قانون العطاء والسخاء دون انتظار مردود أو مقابل، وهو عنوان كتاب أصدره المعهد، وأصبح من الكتب الأكثر مبيعاً وعنوانه: «لماذا تحدث الأشياء الجيدة للناس الطيبين». ويتضمن الكتاب الكثير من القصص والحكم وما يختص بالجانب العلمي ومقياس التقييم الذاتي، وتمت ترجمته إلى أكثر من لغة، ولا يزال مقروءاً، وتتم مناقشته عبر العالم. ورغم وجود آلاف الكتب عن الحب؛ لكنها جميعها كانت تركز على تاريخ الأفكار المنطقية والفلسفية دون الأخذ بعين الاعتبار فكرة البحث العلمي من أجل فهم الحب اللامحدود بطريقة البحث التي تجمع بين علم الوراثة والجينات والعلوم الاجتماعية وعلم النفس الإيجابي، مع الأخذ في الاعتبار، الأفكار الدينية العظيمة والقيم الإنسانية، التي يجب الحفاظ عليها؛ كي لا يصبح مستقبل البشرية في حال غيابها في مواجهة خطر متزايد.الحب اللامحدود هو النقطة الأساسية والمهمة، التي يجب أن يلتقي عندها مستقبل البشرية، وهو الحب الذي يقدمه الإنسان لآخرين لم يقدموا له شيئاً؛ لكنه سيحث الناس على إعادة توجيه مشاعرهم العدائية بعيداً عن بعضهم بحيث يصبح كفاح البشر المشترك ضد الأمراض والمجاعات والفقر والعنف والاعتداءات الأخرى فقط.ويبحث المعهد، من خلال تحقيقات علمية مبتكرة على شكل حوارات تفاعلية تتبع النهج العلمي، عن نوعية الناس الذين يمنحون الآخرين بسخاء؛ ليعرف، عبر هذه الحوارات، إن كانوا يتمتعون بصحة أفضل من غيرهم، وهل يعيشون حياة أطول؟، هل يشفي الحب من الأمراض؟، هل يمكن القول إن الكرم والتعاون يجعلان الإنسان، الذي يسلكهما أكثر صحة من الآخر الذي يغلب عليه طبع الأنانية وحب الذات؟، ما الذي يمكننا أن نكتشفه من خلال البحث في حيوات الأفراد المحبين للآخرين؟إن فكرة المعهد تقوم على أهمية تعليم الأجيال القادمة معنى وطريقة العيش بسلام، وكيف يصبح العطاء قانوناً في حياتهم من أجل حب بلا حدود. basema.younes@gmail.com\n الفئة المتوقعة: \nالفئة المتوقعة: \n\nالثقافة '}]




الثقافة

 67%|██████▋   | 4/6 [00:04<00:02,  1.18s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\n محتوى المقال: \nأبوظبي: «الخليج» أكد عدد من الخبراء والمسؤولين المشاركين في فعاليات جناح جائزة خليفة التربوية أن المعرض أصبح علامة بارزة في مسيرة الفكر والثقافة، وترجم المكانة المرموقة التي تحظى بها أبوظبي كمركز عالمي للإبداع الفكري والإشعاع الحضاري.وشهد جناح الجائزة عدداً من المحاضرات الثقافية وورش العمل التطبيقية التي ترسخ ثقافة التميز لدى مختلف فئات المجتمع.وقالت أمل العفيفي الأمين العام للجائزة: إن البرنامج الثقافي للجائزة شمل محاضرة بعنوان «ثقافة التميز» تحدث فيها الدكتور خالد العبري عضو اللجنة التنفيذية للجائزة حول مسيرة الجائزة منذ انطلاقها في العام 2007 لتشكل بذلك مبادرة وطنية رائدة لغرس ثقافة التميز في الميدان التربوي وتحفيز المعلمين والقيادات التعليمية والأكاديمية بل ومختلف فئات المجتمع على الإبداع، وهو ما تحقق لها بامتياز وجدارة.كما تحدث محمد سالم الظاهري مستشار رئيس دائرة التعليم والمعرفة في امارة أبوظبي في محاضرة بعنوان «زايد والتعليم» عن فكر ورؤية هذا القائد العظيم الذي جعل من التعليم ركيزة أساسية للنهضة الحضارية التي نشهدها، والتي تعتبر نموذجاً يحتذى به إقليمياً ودولياً.وقال الظاهري: عندما نتحدث عن المغفور له الشيخ زايد بن سلطان آل نهيان «طيب الله ثراه» فإننا نقف أمام أحد قادة العالم الذين سطروا بفكرهم ورؤيتهم إنجازات حضارية تفخر بها البشرية، واليوم فإنني في هذه المحاضرة أسلط الضوء فقط على محاور بسيطة تترجم فكر ورؤية القائد المؤسس «طيب الله ثراه». وتابع: أدرك «الشيخ زايد» أنه بدون تعليم أبناء وبنات الوطن فلن تتحقق النهضة المنشودة، ومن هنا وجه «الشيخ زايد» ببناء منظومة من المدارس والمعاهد التعليمية في مختلف مناطق إمارة أبوظبي، فكانت هناك مدارس في المدن والقرى، والتجمعات السكنية في مختلف أرجاء الإمارة.وقدم كل من الدكتور محمد مصطفى أحمد من جامعة الإمارات وعائشة الزعابي من روضة الغدير بمنطقة رأس الخيمة التعليمية ورشة عمل حول «ثقافة التميز»، عرض فيها كل منهما الآليات التي قادتهما لحصد جائزة خليفة التربوية عن فئة الأستاذ الجامعي المتميز في البحث العلمي، وفئة الأداء التعليمي المؤسسي.\n الفئة المتوقعة: \nالفئة المتوقعة: الثقافة '}]


 الثقافة

 83%|████████▎ | 5/6 [00:06<00:01,  1.17s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\n محتوى المقال: \nيمكن القول باطمئنان أن شهر رمضان المبارك هو شهر فن الخط العربي، ففي هذا الشهر الكريم تكثر مهرجانات ومعارض الخط في الكثير من البلدان العربية وربما الإسلامية أيضاً، وذلك لاقتران الخط العربي بدلالات دينية روحية إلى جانب سماته الجمالية التي تعلّق بها فنانون تشكيليون غير عرب رأوا في الخط طاقة إبداعية متميزة عن كل خطوط الأبجديات الحية في العالم.لكن رمضان في الإمارات من حيث حجم هذه المعارض يختلف عن أي بلد عربي آخر، فخلال هذا الشهر تنشط وتتفاعل البرامج اليومية المتعلقة بمهرجان الفنون الإسلامية والذي يتميز بأنه (أي المهرجان) فعالية طويلة تستمر الى شهر وأكثر، وحقيقة الأمر أن المهرجان هو مجموعة مهرجانات إذا اعتبرنا أن سلسلة طويلة من معارض الخط تقام في فترة محددة من العام هي في حقيقتها مهرجانات خطيّة أو خطوطية. فكل معرض له شخصيته وأساليبه الفنية ورؤاه الفكرية والجمالية.المرئي والمسموع على سبيل المثال له صورة حروفية تشكيلية أو صورة خطية تجعل منه فعالية لها وزنها الخاص على أجندات المهرجان.وفي هذه الدورة من مهرجان الفنون الإسلامية لا بد أن نلتفت بقوة الى الخطاطات العربيات اللواتي جئن من شمال إفريقيا ليعرضن للمرة الأولى هنا في الشارقة موئل فن الخط العربي وعاصمة الكتاب والمسرح.هناك أيضاً معرض دروب الحروف.. وهو الآخر فضاء خطّي يمثل.. تجوالاً بصرياً يتماوج مع المعاني السامية للنصوص المختارة، كما يعبّر عن فضاءات الخط العربي ذات الخصوصية المغاربية.. كما جاء في تعريف هذا المعرض المهرجان في كتيبات دائرة الثقافة والإعلام في الشارقة.ولا ننسى تلك الروح العربية الأصيلة المبثوثة في أعمال معرض جوانيات للفنان راشد النقبي، وكذلك معرض همسات فاس للفنان جاسم ربيع، وأيضاً معرض نداء المآذن.. .. بوح ملاصق للروح، مسهب في تعرية الذات من دنس الدنيا وركامها.... إلخ.إذن.. معارض تلو معارض، أو مجموعة مهرجانات عرض في مهرجان واحد عنوانه العريض فلك الفسيفساء يميّز الشارقة ويجعلها بكل جدارة المكان المثالي لنمو وتنمية فن الخط العربي بكل أبعاده الروحية والتشكيلية والجمالية.ولا تتوقف عجلة الخط العربي عند مهرجان فلك الفسيفساء، بل يلتقي في الإمارات 30 خطاطاً في تقليد سنوي أطلقته وزارة الثقافة والشباب وتنمية المجتمع لكتابة نسخة واحدة من القرآن الكريم، وفي دبي يعرض اليوم 29 فناناً تجارب خطية ذات اجتهادات تجريدية تؤشر على الطاقة الإبداعية الظاهرة والباطنة في انسياب الخط العربي.الإمارات من أبرز البلدان العربية وغير العربية التي تعطي فن الخط كل هذا الاهتمام وكل هذه العناية الثقافية في إطار توجه ثقافي شامل تفخر به البلاد وتعتز.\n الفئة المتوقعة: \nالفئة المتوقعة: الثقافة '}]


 الثقافة

100%|██████████| 6/6 [00:06<00:00,  1.14s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\n محتوى المقال: \nيشارك المسرحي الشاب رامي مجدي في مهرجان الشارقة للمسرحيات القصيرة بعرض الواشي لبريخت في ثاني تجربة إخراجية، بعد أن أخرج في الدورة الأولى من المهرجان مسرحية الغرباء لا يشربون القهوة التي قدمته موهبة إخراجية يعوّل عليها في المستقبل، ويقول مجدي عن هذه المشاركة: لقد كانت تجربتي في إخراج (الغرباء لا يشربون القهوة) مفيدة جداً وتعرفت من خلالها إلى كثير من خفايا العملية الإخراجية، خصوصاً طرق التعامل مع النص، وأساليب قيادة الفريق وتوجيه الممثلين وغيرها، وقد كان الانطباع العام لدى النقاد خلال المهرجان أن العمل جيد، ورغم أن العرض استبعد من الجائزة لأنه تجاوز الوقت المحدد للمسرحيات القصيرة، إلا أن تلك التجربة أفادتني كثيراً، وشجعتني على مواصلة المغامرة الإخراجية في هذا العمل الجديد، وقد اخترت نصاً لواحد من أعمدة المسرح العالمي وقائد مدرسة التجريب فيه .وعن مضمون العرض الجديد يقول مجدي: النص مكتوب سنة ،1938 قبل أن يتجه بريخت اتجاهه التجريبي، فهو يمكن أن يصنّف في باب المرحلة الواقعية لهذا الكاتب، لكنني خلال العرض أحاول أن أضفي عليه نوعاً من التجريب، كما أعمد إلى إعطائه صبغة كوميدية عن طريق التناقض في المواقف والمبالغة في الأداء، وهو يتناول حياة أسرة ألمانية تتألف من أب وأم وطفل وخادمة، ويصوّر الكم الهائل من الرعب الذي كان يسيطر على المجتمع أثناء الفترة النازية، فقد كان محرماً على الفرد العادي الكلام في السياسة، وكان المخبرون مبثوثين في كل مكان، وفي إحدى المرات يتكلم الأب سهواً بألفاظ سيئة عن هتلر في حضور الطفل، ثم يكتشف خطأه ويعيش فترات رعب خوفاً من أن يتكلم الطفل بتلك الألفاظ أمام الغير فيصل الأمر إلى مخبري هتلر، ما يجعل الأب يعيش حالة من حالات الهلوسة .يشارك في التمثيل في الواشي هاني الطمباري، ودنيا، وأنس عبدالله، وولاء حامد، وعمر الفاروق، ويشرف على تدريبات المهرجان الفنان يحيى الحاج، كما يشارك رامي مجدي كممثل في عرض آخر من عروض المهرجان هو حديقة الحيوان للكاتب الإنجليزي إدوارد ألبي، وهو من إخراج ماهر مزوق .يدين رامي مجدي الذي يحمل شهادة في الفلسفة وعلم النفس بكثير من تجاربه المسرحية لإدارة المسرح في دائرة الثقافة والإعلام في الشارقة التي فتحت له باب التمثيل عن طريق الورش التي نظمتها خلال السنوات الماضية، وكان من نتائجها إنشاء فرقة مسرحية تابعة للدائرة كان رامي أحد أعضائها المتميزين، ويقول عن ذلك: كانت لي تجارب سابقة في مجال المسرح أثناء فترة الدراسة الجامعية، لكنها لم تكن مؤسسة بسبب عدم وجود الدعم التدريبي، لكنني وجدت في البرامج التدريبية والورش التي تقيمها دائرة الثقافة والإعلام ضالتي، فكنت حاضراً فيها باستمرار، وقد فتحت لي الباب واسعاً للتمثيل وفنون المسرح بشكل عام، وانتميت إلى فرقة المسرح التابعة للدائرة وشاركت معها في كثير من العروض تحت إشراف الفنان الرشيد أحمد عيسى، كما كانت الورشة المتكاملة التي تقيمها إدارة المسرح قبل مهرجان المسرحيات القصيرة مناسبة للاحتكاك بعدد من كبار المسرحيين العرب الذين قدموا لنا تجاربهم المختلفة خلال الدورتين السابقتين، مثل خالد جلال، وجان داوود، وإبراهيم سالم، ويحيى الحاج، وهي خبرات تلخص تجارب المدارس المسرحية العربية على اختلافها وهو تنوع من النادر أن يحصل عليه دارسو المسرح، لأن الأكاديميات تقدم تجارب بلد واحد، وهو ما يعطينا قدرة على التعامل مع مختلف المدارس والاستفادة منها .\n الفئة المتوقعة: '}]

In [ ]:
pred = []

max_length = tokenizer.model_max_length
for i in tqdm(range(len(data))):
    prompt = data.iloc[i]["prompt"]
    # prompt = prompt[:max_length]
    # result = pipe(prompt, pad_token_id=pipe.tokenizer.eos_token_id)
    result = pipe(prompt[:tokenizer.model_max_length], truncation=True, pad_token_id=pipe.tokenizer.eos_token_id)
    answer = result[0]['generated_text'].split("الفئة المتوقعة:")[-1].strip()

    pred.append(answer)

100%|██████████| 1000/1000 [19:42<00:00,  1.18s/it]

In [ ]:
pred_zero = pd.DataFrame()
pred_zero['Predicted'] = pred
pred_zero['Predicted'].value_counts()

Predicted
السياسة                                                                                133
6. الرياضة                                                                             117
3. الطب                                                                                116
التكنولوجيا                                                                             99
                                                                                        97
الثقافة                                                                                 92
المال                                                                                   79
4. السياسة                                                                              71
7. التكنولوجيا                                                                          43
5. الدين                                                                                28
الدين                                                                                   27
1. الثقافة                                                                              25
2. المال                                                                                23
الرياضة                                                                                 15
الطب                                                                                     5
1. السياسة                                                                               3
7. الرياضة                                                                               2
1. الثقافة\n\nالتبرير:\nالمقال                                                           2
1. المال                                                                                 2
2                                                                                        2
الفئة: الدين                                                                             2
الفئة المتوقعة لهذا المقال هي: **الدين**                                                 2
الفئة: **الثقافة**                                                                       1
1. الصحة\n\nالمقال يتحدث عن مسيرة "                                                      1
1. الكوارث الطبيعية                                                                      1
الفئة: السياسة                                                                           1
1. الثقافة \n\nالسبب: يتناول المقال                                                      1
الفئة: الرياضة                                                                           1
بناءً على محتوى المقال، يمكن تصنيف المقال تحت فئة "المال".                               1
1. الجريمة                                                                               1
السياحة                                                                                  1
الموضوع الرئيسي للمقال هو:\nالمال                                                        1
1. الزراعة                                                                               1
الموضوع الرئيسي للمقال هو أسعار النفط وتوقعاتها المستقبلية. لذلك، الفئة المناسبة هي      1
الموضوع الرئيسي للمقال هو مشروع ترامواي الدار البيضاء، وهو مشروع بنية تحت                1
**الدين**                                                                                1
1. الثقافة\n\nالمقال يتحدث عن تجربة شخصية                                                1
Name: count, dtype: int64

In [ ]:
nor_pre = []
for pr in pred_zero['Predicted']:
  if "الرياضة" in pr:
    nor_pre.append("Sports")
  elif "الصحة" in pr:
    nor_pre.append("Medical")
  elif "الطب" in pr:
    nor_pre.append("Medical")
  elif "الثقافة" in pr:
    nor_pre.append("Culture")
  elif "المال" in pr:
    nor_pre.append("Finance")
  elif "السياسة" in pr:
    nor_pre.append("Politics")
  elif "الدين" in pr:
    nor_pre.append("Religion")
  elif "التكنولوجيا" in pr:
    nor_pre.append("Tech")
  else:
    nor_pre.append("Unclassified")

In [ ]:
pred_zero['Normalized Prediction'] = nor_pre

In [ ]:
pred_zero['Normalized Prediction'].value_counts()

Normalized Prediction
Politics        208
Tech            142
Sports          135
Medical         123
Culture         122
Finance         106
Unclassified    104
Religion         60
Name: count, dtype: int64

In [ ]:
pred_zero.to_csv('Allam Zero Shot News Classification.xlsx', index = False)

In [ ]:
true = pd.read_excel('sampled_data.xlsx')
y_true = true['subdirectory'].values
print(classification_report(y_true, pred_zero['Normalized Prediction'].values, digits = 4))

              precision    recall  f1-score   support

     Culture     0.8525    0.6933    0.7647       150
     Finance     0.8585    0.6067    0.7109       150
     Medical     0.8699    0.7133    0.7839       150
    Politics     0.6538    0.9067    0.7598       150
    Religion     0.9500    0.5700    0.7125       100
      Sports     0.8963    0.8067    0.8491       150
        Tech     0.8380    0.7933    0.8151       150
Unclassified     0.0000    0.0000    0.0000         0

    accuracy                         0.7350      1000
   macro avg     0.7399    0.6362    0.6745      1000
weighted avg     0.8404    0.7350    0.7738      1000

# Pred Few Shot

In [ ]:
data2 = pd.read_excel('News Classification Jais Few Shot.xlsx')

In [ ]:
from tqdm import tqdm
max_length = tokenizer.model_max_length
for i in tqdm(range(len(data2[:6]))):
    prompt = data2.iloc[i]["prompt"]
    prompt = prompt[:max_length]
    result = pipe(prompt, pad_token_id=pipe.tokenizer.eos_token_id)
    answer = result[0]['generated_text'].split("الفئة المتوقعة:")[-1].lower()
    print('\n')
    print(result)
    print('\n')
    print(answer)

 17%|█▋        | 1/6 [00:02<00:12,  2.40s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nالفئة المتوقعة: الدين\n\n\n محتوى المقال: \nاستقبل الوسط المسرحي الإماراتي فوز الإمارات برئاسة الهيئة الدولية للمسرح بالكثير من الزهو والسعادة، وأعرب عدد من المشتغلين في المسرح عن فرحهم بهذا الإنجاز الذي يضاف إلى الرصيد الفني المحلي الذي قام على جهود عناصر مسرحية مسكونة بالجدية والمسؤولية .وأشار المسرحيون الإماراتيون إلى الجهود المتواصلة التي بذلها زميلهم محمد سيف الأفخم محلياً وعربياً ودولياً إلى أن قطفت الإمارات هذا النجاح الذي تستحقه، وتفوّقت على ست دول ذات رصيد تاريخي في فن المسرح .وقال د . حبيب غلوم: "نبارك لمحمد الأفخم ولأنفسنا اختياره رئيساً للهيئة الدولية للمسرح، وهو ولا شك ثمرة لاجتهاد وعطاء قيم، ونتمنى أن يترجم طموح من اختاروه، وأن تخطو به الإمارات نحو الأمام، من خلال فعل مسرحي متصل ومستمر يغطي كامل السنة، لأننا اليوم نحتاج إلى عمل مسرحي يتواصل خارج المهرجانات، ويوجد في الساحة حراكا يومياً معمماً على الفرق والمدن كافة" .المسرحي سلطان النيادي قال: "الأفخم من الشباب الإماراتيين الذين كرسوا جهداً كبيراً للثقافة والمسرح، ومن عادة ابن الإمارات أن يتميز إذا كرس جهده في اتجاه معين، نحن نبارك له ولأنفسنا هذا النجاح، ونعول عليه في عطاء أكبر وزيادة واتساع في الفعل المسرحي الإماراتي، وكذلك نأمل أن يقدم بصمة دولية على مستوى الهيئة التي يرأسها" .وقال حميد سمبيج: "هذا الفوز هو ثمرة جهد بذله الأفخ والعناصر المسرحية الإماراتية، من خلال عمله ومسؤولياته، وكذلك جهد الساحة المسرحية الإماراتية ككل، تلك الساحة التي هيأت الظروف لهذا الفوز من خلال السمعة الجيدة التي أصبح يحظى بها المسرح الإماراتي، نتيجة فعل مسرحي متميز ومستمر على مدى العام كان انطلاقه من الشارقة وعم اليوم جميع ربوع البلاد حتى أصبحت الإمارات عاصمة المسرح في الوطن العربي، بل عاصمة لنشاط ثقافي له أبعاد عربية وعالمية" .وأضاف سمبيج: نحن نفخر كثيراً بهذا الفوز، ونعتبره فوزاً للإمارات عامة، وهو فوز طبيعي ومستحق، لأن محمد الأفحم عمل بجهد واجتهاد وارتقى بمهرجان الفجيرة للمونودراما إلى أن أصبح فعلاً مسرحياً عالمياً، وأنا على يقين أن هذا الفوز سيثري الهيئة الدولية للمسرح بخبرة إماراتية جديدة .الفنان عبدالله زيد قال: "النجاح وليد المثابرة، ولن يصل إلى القمة من ظل قابعا في السفح، ومحمد الأفخم مثابر ومجتهد، وكل الوسط المسرحي الإماراتي مثابر ومجتهد، وهو مثال للشاب الإماراتي المفعم بالعطاء والحماسة للعمل، وليس غريباً على أبناء الإمارات الفوز واستحقاق المناصب العالية، نحن فخورون بأن يفوز أحد رجالنا المتميزين، وأن تتربع الإمارات على رئاسة هذه الهيئة المسرحية الدولية" .وقال د . هيثم الخواجه: "الحراك المسرحي في دولة الإمارات العربية المتحدة الذي بدأ منذ عقدين تقريباً حقق الكثير من النجاحات، سواء فيما يتعلق بكتابة النص المسرحي أو العرض المسرحي أو ما يمهد لذلك من ورش ومختبرات ومهرجانات، والذي جعل الحراك المسرحي متميزاً أيضاً هو البدء من المسرح المدرسي إلى مسرح الأطفال إلى الجامعي إلى الشباب إلى مسرح الكبار، هذه البنية المتكاملة جعلت الحركة المسرحية في الإمارات قابلة للتطور والنمو ما حقق الفوز في كثيرمن العروض والجوائز الكبيرة، ولا ريب أن صاحب السمو الشيخ الدكتور سلطان بن محمد القاسمي عضو المجلس الأعلى حاكم الشارقة، الذي قدم دعماً مادياً ومعنوياً وإبداعياً للمسرح أضاف الكثير إلى هذا الفن العظيم" .وأضاف الخواجة: كل ذلك أهّل الحركة المسرحية في الإمارات لأن تكون مضيئة بشكل حقيقي، وما رأيناه أن هذا الفوز جاء بشكل حقيقي، وما أراه أن هذا الفوز تستحقه دولة الإمارات بجدارة، طالما أن ما يحيط بها لم يصل إلى هذا المستوى من العطاء .\n الفئة المتوقعة: \nالفئة المتوقعة: الثقافة '}]


 الثقافة

 33%|███▎      | 2/6 [00:04<00:08,  2.16s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nالفئة المتوقعة: الدين\n\n\n محتوى المقال: \nاستضاف مركز الشارقة لفن الخط العربي والزخرفة مساء أمس الأول معرض ( حرف ولون ) لأعمال منتسبي المركز التابع لمجمع الشارقة للآداب والفنون، بحضور هنا سيف السويدي رئيسة هيئة البيئة والمحميات الطبيعية وعضو المجلس التنفيذي، وهشام المظلوم رئيس المجمع.شارك في المعرض أربعون منتسباً للمركز، وبلغ عدد الأعمال 50 عملاً خطياً وفق خطوط وزخارف متنوعة ومختلفة في المدارس والاتجاهات، وتبدو في المعرض الذي يضم مجموعة من اللوحات الخطية قضية تأكيد الابتكار جلية بالرغم من الالتزام الواضح بميزان القواعد ونواظم كل نوع من الخطوط المستهدفة للتعبير عن التراكيب البصرية اللافتة للخط العربي الأصيل، ولوحظ أن المواضيع المطروحة متعددة بدءاً من الآيات الكريمة وانتهاء بتشكيل مجرد للأحرف، إلا أن اللون كما هو واضح في عنوان المعرض كان حاضراً في كثير من اللوحات في خطوة للتفرد ولتنويع الإيقاع، وكان لخط النسخ والديواني الجلي حضور واسع ومهم بين الخطوط والمعروضات. رافق المعرض ورشة «خط» أشرفت عليها مروة منذر، وطلال السباعي، وشارك فيها مجموعة من الحضور، حيث شاهدوا تطبيقاً عملياً لكتابة بعض العبارات والأسماء.\n الفئة المتوقعة: \nالفئة المتوقعة: الثقافة '}]


 الثقافة

 50%|█████     | 3/6 [00:06<00:06,  2.16s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nالفئة المتوقعة: الدين\n\n\n محتوى المقال: \nباسمة يونس قد يبدو العنوان اسماً لرواية؛ لكنه الاسم الذي أطلقته جامعة كيس ويسترن ريزرف في ولاية كليفلاند على معهد أسسته عام 2001؛ للتوعية بأهمية الحب، الذي لا يحده شيء من خلال البحث في معنى هذا الحب، وكل عناصره المحيطة به. وتعرف هذه المؤسسة الحب في رسالتها على أنه الشعور الداخلي الذي يجعل من سعادة شخص آخر وطمأنينته واستقراره دافعاً للشعور بالسعادة، بما يعني أن من يسعد لسعادة شخص آخر فهو يحبه حباً حقيقياً ومطلقاً.وقد تأسست فكرة المعهد على قانون بسيط مفاده، أن الحب اللامحدود يقوم على قانون العطاء والسخاء دون انتظار مردود أو مقابل، وهو عنوان كتاب أصدره المعهد، وأصبح من الكتب الأكثر مبيعاً وعنوانه: «لماذا تحدث الأشياء الجيدة للناس الطيبين». ويتضمن الكتاب الكثير من القصص والحكم وما يختص بالجانب العلمي ومقياس التقييم الذاتي، وتمت ترجمته إلى أكثر من لغة، ولا يزال مقروءاً، وتتم مناقشته عبر العالم. ورغم وجود آلاف الكتب عن الحب؛ لكنها جميعها كانت تركز على تاريخ الأفكار المنطقية والفلسفية دون الأخذ بعين الاعتبار فكرة البحث العلمي من أجل فهم الحب اللامحدود بطريقة البحث التي تجمع بين علم الوراثة والجينات والعلوم الاجتماعية وعلم النفس الإيجابي، مع الأخذ في الاعتبار، الأفكار الدينية العظيمة والقيم الإنسانية، التي يجب الحفاظ عليها؛ كي لا يصبح مستقبل البشرية في حال غيابها في مواجهة خطر متزايد.الحب اللامحدود هو النقطة الأساسية والمهمة، التي يجب أن يلتقي عندها مستقبل البشرية، وهو الحب الذي يقدمه الإنسان لآخرين لم يقدموا له شيئاً؛ لكنه سيحث الناس على إعادة توجيه مشاعرهم العدائية بعيداً عن بعضهم بحيث يصبح كفاح البشر المشترك ضد الأمراض والمجاعات والفقر والعنف والاعتداءات الأخرى فقط.ويبحث المعهد، من خلال تحقيقات علمية مبتكرة على شكل حوارات تفاعلية تتبع النهج العلمي، عن نوعية الناس الذين يمنحون الآخرين بسخاء؛ ليعرف، عبر هذه الحوارات، إن كانوا يتمتعون بصحة أفضل من غيرهم، وهل يعيشون حياة أطول؟، هل يشفي الحب من الأمراض؟، هل يمكن القول إن الكرم والتعاون يجعلان الإنسان، الذي يسلكهما أكثر صحة من الآخر الذي يغلب عليه طبع الأنانية وحب الذات؟، ما الذي يمكننا أن نكتشفه من خلال البحث في حيوات الأفراد المحبين للآخرين؟إن فكرة المعهد تقوم على أهمية تعليم الأجيال القادمة معنى وطريقة العيش بسلام، وكيف يصبح العطاء قانوناً في حياتهم من أجل حب بلا حدود. basema.younes@gmail.com\n الفئة المتوقعة: \nالفئة المتوقعة: الدين '}]


 الدين

 67%|██████▋   | 4/6 [00:08<00:04,  2.04s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nالفئة المتوقعة: الدين\n\n\n محتوى المقال: \nأبوظبي: «الخليج» أكد عدد من الخبراء والمسؤولين المشاركين في فعاليات جناح جائزة خليفة التربوية أن المعرض أصبح علامة بارزة في مسيرة الفكر والثقافة، وترجم المكانة المرموقة التي تحظى بها أبوظبي كمركز عالمي للإبداع الفكري والإشعاع الحضاري.وشهد جناح الجائزة عدداً من المحاضرات الثقافية وورش العمل التطبيقية التي ترسخ ثقافة التميز لدى مختلف فئات المجتمع.وقالت أمل العفيفي الأمين العام للجائزة: إن البرنامج الثقافي للجائزة شمل محاضرة بعنوان «ثقافة التميز» تحدث فيها الدكتور خالد العبري عضو اللجنة التنفيذية للجائزة حول مسيرة الجائزة منذ انطلاقها في العام 2007 لتشكل بذلك مبادرة وطنية رائدة لغرس ثقافة التميز في الميدان التربوي وتحفيز المعلمين والقيادات التعليمية والأكاديمية بل ومختلف فئات المجتمع على الإبداع، وهو ما تحقق لها بامتياز وجدارة.كما تحدث محمد سالم الظاهري مستشار رئيس دائرة التعليم والمعرفة في امارة أبوظبي في محاضرة بعنوان «زايد والتعليم» عن فكر ورؤية هذا القائد العظيم الذي جعل من التعليم ركيزة أساسية للنهضة الحضارية التي نشهدها، والتي تعتبر نموذجاً يحتذى به إقليمياً ودولياً.وقال الظاهري: عندما نتحدث عن المغفور له الشيخ زايد بن سلطان آل نهيان «طيب الله ثراه» فإننا نقف أمام أحد قادة العالم الذين سطروا بفكرهم ورؤيتهم إنجازات حضارية تفخر بها البشرية، واليوم فإنني في هذه المحاضرة أسلط الضوء فقط على محاور بسيطة تترجم فكر ورؤية القائد المؤسس «طيب الله ثراه». وتابع: أدرك «الشيخ زايد» أنه بدون تعليم أبناء وبنات الوطن فلن تتحقق النهضة المنشودة، ومن هنا وجه «الشيخ زايد» ببناء منظومة من المدارس والمعاهد التعليمية في مختلف مناطق إمارة أبوظبي، فكانت هناك مدارس في المدن والقرى، والتجمعات السكنية في مختلف أرجاء الإمارة.وقدم كل من الدكتور محمد مصطفى أحمد من جامعة الإمارات وعائشة الزعابي من روضة الغدير بمنطقة رأس الخيمة التعليمية ورشة عمل حول «ثقافة التميز»، عرض فيها كل منهما الآليات التي قادتهما لحصد جائزة خليفة التربوية عن فئة الأستاذ الجامعي المتميز في البحث العلمي، وفئة الأداء التعليمي المؤسسي.\n الفئة المتوقعة: \nالثقافة '}]



الثقافة

 83%|████████▎ | 5/6 [00:10<00:02,  2.09s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nالفئة المتوقعة: الدين\n\n\n محتوى المقال: \nيمكن القول باطمئنان أن شهر رمضان المبارك هو شهر فن الخط العربي، ففي هذا الشهر الكريم تكثر مهرجانات ومعارض الخط في الكثير من البلدان العربية وربما الإسلامية أيضاً، وذلك لاقتران الخط العربي بدلالات دينية روحية إلى جانب سماته الجمالية التي تعلّق بها فنانون تشكيليون غير عرب رأوا في الخط طاقة إبداعية متميزة عن كل خطوط الأبجديات الحية في العالم.لكن رمضان في الإمارات من حيث حجم هذه المعارض يختلف عن أي بلد عربي آخر، فخلال هذا الشهر تنشط وتتفاعل البرامج اليومية المتعلقة بمهرجان الفنون الإسلامية والذي يتميز بأنه (أي المهرجان) فعالية طويلة تستمر الى شهر وأكثر، وحقيقة الأمر أن المهرجان هو مجموعة مهرجانات إذا اعتبرنا أن سلسلة طويلة من معارض الخط تقام في فترة محددة من العام هي في حقيقتها مهرجانات خطيّة أو خطوطية. فكل معرض له شخصيته وأساليبه الفنية ورؤاه الفكرية والجمالية.المرئي والمسموع على سبيل المثال له صورة حروفية تشكيلية أو صورة خطية تجعل منه فعالية لها وزنها الخاص على أجندات المهرجان.وفي هذه الدورة من مهرجان الفنون الإسلامية لا بد أن نلتفت بقوة الى الخطاطات العربيات اللواتي جئن من شمال إفريقيا ليعرضن للمرة الأولى هنا في الشارقة موئل فن الخط العربي وعاصمة الكتاب والمسرح.هناك أيضاً معرض دروب الحروف.. وهو الآخر فضاء خطّي يمثل.. تجوالاً بصرياً يتماوج مع المعاني السامية للنصوص المختارة، كما يعبّر عن فضاءات الخط العربي ذات الخصوصية المغاربية.. كما جاء في تعريف هذا المعرض المهرجان في كتيبات دائرة الثقافة والإعلام في الشارقة.ولا ننسى تلك الروح العربية الأصيلة المبثوثة في أعمال معرض جوانيات للفنان راشد النقبي، وكذلك معرض همسات فاس للفنان جاسم ربيع، وأيضاً معرض نداء المآذن.. .. بوح ملاصق للروح، مسهب في تعرية الذات من دنس الدنيا وركامها.... إلخ.إذن.. معارض تلو معارض، أو مجموعة مهرجانات عرض في مهرجان واحد عنوانه العريض فلك الفسيفساء يميّز الشارقة ويجعلها بكل جدارة المكان المثالي لنمو وتنمية فن الخط العربي بكل أبعاده الروحية والتشكيلية والجمالية.ولا تتوقف عجلة الخط العربي عند مهرجان فلك الفسيفساء، بل يلتقي في الإمارات 30 خطاطاً في تقليد سنوي أطلقته وزارة الثقافة والشباب وتنمية المجتمع لكتابة نسخة واحدة من القرآن الكريم، وفي دبي يعرض اليوم 29 فناناً تجارب خطية ذات اجتهادات تجريدية تؤشر على الطاقة الإبداعية الظاهرة والباطنة في انسياب الخط العربي.الإمارات من أبرز البلدان العربية وغير العربية التي تعطي فن الخط كل هذا الاهتمام وكل هذه العناية الثقافية في إطار توجه ثقافي شامل تفخر به البلاد وتعتز.\n الفئة المتوقعة: \nالفئة المتوقعة: الثقافة '}]


 الثقافة

100%|██████████| 6/6 [00:12<00:00,  2.15s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nالفئة المتوقعة: الدين\n\n\n محتوى المقال: \nيشارك المسرحي الشاب رامي مجدي في مهرجان الشارقة للمسرحيات القصيرة بعرض الواشي لبريخت في ثاني تجربة إخراجية، بعد أن أخرج في الدورة الأولى من المهرجان مسرحية الغرباء لا يشربون القهوة التي قدمته موهبة إخراجية يعوّل عليها في المستقبل، ويقول مجدي عن هذه المشاركة: لقد كانت تجربتي في إخراج (الغرباء لا يشربون القهوة) مفيدة جداً وتعرفت من خلالها إلى كثير من خفايا العملية الإخراجية، خصوصاً طرق التعامل مع النص، وأساليب قيادة الفريق وتوجيه الممثلين وغيرها، وقد كان الانطباع العام لدى النقاد خلال المهرجان أن العمل جيد، ورغم أن العرض استبعد من الجائزة لأنه تجاوز الوقت المحدد للمسرحيات القصيرة، إلا أن تلك التجربة أفادتني كثيراً، وشجعتني على مواصلة المغامرة الإخراجية في هذا العمل الجديد، وقد اخترت نصاً لواحد من أعمدة المسرح العالمي وقائد مدرسة التجريب فيه .وعن مضمون العرض الجديد يقول مجدي: النص مكتوب سنة ،1938 قبل أن يتجه بريخت اتجاهه التجريبي، فهو يمكن أن يصنّف في باب المرحلة الواقعية لهذا الكاتب، لكنني خلال العرض أحاول أن أضفي عليه نوعاً من التجريب، كما أعمد إلى إعطائه صبغة كوميدية عن طريق التناقض في المواقف والمبالغة في الأداء، وهو يتناول حياة أسرة ألمانية تتألف من أب وأم وطفل وخادمة، ويصوّر الكم الهائل من الرعب الذي كان يسيطر على المجتمع أثناء الفترة النازية، فقد كان محرماً على الفرد العادي الكلام في السياسة، وكان المخبرون مبثوثين في كل مكان، وفي إحدى المرات يتكلم الأب سهواً بألفاظ سيئة عن هتلر في حضور الطفل، ثم يكتشف خطأه ويعيش فترات رعب خوفاً من أن يتكلم الطفل بتلك الألفاظ أمام الغير فيصل الأمر إلى مخبري هتلر، ما يجعل الأب يعيش حالة من حالات الهلوسة .يشارك في التمثيل في الواشي هاني الطمباري، ودنيا، وأنس عبدالله، وولاء حامد، وعمر الفاروق، ويشرف على تدريبات المهرجان الفنان يحيى الحاج، كما يشارك رامي مجدي كممثل في عرض آخر من عروض المهرجان هو حديقة الحيوان للكاتب الإنجليزي إدوارد ألبي، وهو من إخراج ماهر مزوق .يدين رامي مجدي الذي يحمل شهادة في الفلسفة وعلم النفس بكثير من تجاربه المسرحية لإدارة المسرح في دائرة الثقافة والإعلام في الشارقة التي فتحت له باب التمثيل عن طريق الورش التي نظمتها خلال السنوات الماضية، وكان من نتائجها إنشاء فرقة مسرحية تابعة للدائرة كان رامي أحد أعضائها المتميزين، ويقول عن ذلك: كانت لي تجارب سابقة في مجال المسرح أثناء فترة الدراسة الجامعية، لكنها لم تكن مؤسسة بسبب عدم وجود الدعم التدريبي، لكنني وجدت في البرامج التدريبية والورش التي تقيمها دائرة الثقافة والإعلام ضالتي، فكنت حاضراً فيها باستمرار، وقد فتحت لي الباب واسعاً للتمثيل وفنون المسرح بشكل عام، وانتميت إلى فرقة المسرح التابعة للدائرة وشاركت معها في كثير من العروض تحت إشراف الفنان الرشيد أحمد عيسى، كما كانت الورشة المتكاملة التي تقيمها إدارة المسرح قبل مهرجان المسرحيات القصيرة مناسبة للاحتكاك بعدد من كبار المسرحيين العرب الذين قدموا لنا تجاربهم المختلفة خلال الدورتين السابقتين، مثل خالد جلال، وجان داوود، وإبراهيم سالم، ويحيى الحاج، وهي خبرات تلخص تجارب المدارس المسرحية العربية على اختلافها وهو تنوع من النادر أن يحصل عليه دارسو المسرح، لأن الأكاديميات تقدم تجارب بلد واحد، وهو ما يعطينا قدرة على التعامل مع مختلف المدارس والاستفادة منها .\n الفئة المتوقعة: \nالفئة المتوقعة: الثقافة '}]


 الثقافة

In [ ]:
pred = []

max_length = tokenizer.model_max_length
for i in tqdm(range(len(data2))):
    prompt = data2.iloc[i]["prompt"]
    # prompt = prompt[:max_length]
    # result = pipe(prompt, pad_token_id=pipe.tokenizer.eos_token_id)
    result = pipe(prompt[:tokenizer.model_max_length], truncation=True, pad_token_id=pipe.tokenizer.eos_token_id)
    answer = result[0]['generated_text'].split("الفئة المتوقعة:")[-1].strip()

    pred.append(answer)

 85%|████████▌ | 853/1000 [32:16<05:22,  2.19s/it]This is a friendly reminder - the current text generation call will exceed the model's predefined maximum length (4096). Depending on the model, you may observe exceptions, performance degradation, or nothing at all.
100%|██████████| 1000/1000 [37:32<00:00,  2.25s/it]

In [ ]:
pred_few = pd.DataFrame()
pred_few['Predicted'] = pred
pred_few['Predicted'].value_counts()

Predicted
السياسة                                                             113
التكنولوجيا                                                         112
الدين                                                               110
المال                                                                81
الثقافة                                                              81
                                                                   ...
المثال 8\nمحتوى المقال:\nأعرب رئيس الوزراء اللبناني سعد               1
المثال 8\nمحتوى المقال:\nأعلنت وزارة الداخلية السعودية عن بدء         1
محتوى المقال:\n\nتحدث المقال عن اكتشاف بحيرة تحت الجليد في القطب      1
مثال 8\nمحتوى المقال:\nأعلن وزير الصحة السعودي،                       1
المثال 8\nمحتوى المقال:\nأعلنت شركة "أوبر"                            1
Name: count, Length: 220, dtype: int64

In [ ]:
nor_pre = []
for pr in pred_few['Predicted']:
  if "الرياضة" in pr:
    nor_pre.append("Sports")
  elif "الصحة" in pr:
    nor_pre.append("Medical")
  elif "الطب" in pr:
    nor_pre.append("Medical")
  elif "الثقافة" in pr:
    nor_pre.append("Culture")
  elif "المال" in pr:
    nor_pre.append("Finance")
  elif "السياسة" in pr:
    nor_pre.append("Politics")
  elif "الدين" in pr:
    nor_pre.append("Religion")
  elif "التكنولوجيا" in pr:
    nor_pre.append("Tech")
  else:
    nor_pre.append("Unclassified")

In [ ]:
pred_few['Normalized Prediction'] = nor_pre
pred_few['Normalized Prediction'].value_counts()

Normalized Prediction
Unclassified    289
Religion        116
Politics        116
Tech            112
Medical         108
Finance          98
Culture          86
Sports           75
Name: count, dtype: int64

In [ ]:
pred_few.to_csv('Allam Few Shot News Classification.xlsx', index = False)

In [ ]:
print(classification_report(y_true, pred_few['Normalized Prediction'].values, digits = 4))

              precision    recall  f1-score   support

     Culture     0.9302    0.5333    0.6780       150
     Finance     0.8469    0.5533    0.6694       150
     Medical     0.7500    0.5400    0.6279       150
    Politics     0.8190    0.6333    0.7143       150
    Religion     0.7155    0.8300    0.7685       100
      Sports     0.9467    0.4733    0.6311       150
        Tech     0.9286    0.6933    0.7939       150
Unclassified     0.0000    0.0000    0.0000         0

    accuracy                         0.5970      1000
   macro avg     0.7421    0.5321    0.6104      1000
weighted avg     0.8548    0.5970    0.6940      1000

# CoT

In [ ]:
pipe = pipeline(task="text-generation",
                model=model,
                tokenizer=tokenizer,
                max_new_tokens=50,
                temperature=0.2
               )

Device set to use cuda:0

In [ ]:
data3 = pd.read_excel('News Classification Jais CoT.xlsx')

In [ ]:
from tqdm import tqdm
max_length = tokenizer.model_max_length
for i in tqdm(range(len(data3[:20]))):
    prompt = data3.iloc[i]["prompt"]
    prompt = prompt[:max_length]
    result = pipe(prompt, pad_token_id=pipe.tokenizer.eos_token_id)
    answer = result[0]['generated_text'].split("الفئة المتوقعة:")[-1].lower()
    print('\n')
    print(result)
    print('\n')
    print(answer)

  5%|▌         | 1/20 [00:05<01:39,  5.25s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nاستقبل الوسط المسرحي الإماراتي فوز الإمارات برئاسة الهيئة الدولية للمسرح بالكثير من الزهو والسعادة، وأعرب عدد من المشتغلين في المسرح عن فرحهم بهذا الإنجاز الذي يضاف إلى الرصيد الفني المحلي الذي قام على جهود عناصر مسرحية مسكونة بالجدية والمسؤولية .وأشار المسرحيون الإماراتيون إلى الجهود المتواصلة التي بذلها زميلهم محمد سيف الأفخم محلياً وعربياً ودولياً إلى أن قطفت الإمارات هذا النجاح الذي تستحقه، وتفوّقت على ست دول ذات رصيد تاريخي في فن المسرح .وقال د . حبيب غلوم: "نبارك لمحمد الأفخم ولأنفسنا اختياره رئيساً للهيئة الدولية للمسرح، وهو ولا شك ثمرة لاجتهاد وعطاء قيم، ونتمنى أن يترجم طموح من اختاروه، وأن تخطو به الإمارات نحو الأمام، من خلال فعل مسرحي متصل ومستمر يغطي كامل السنة، لأننا اليوم نحتاج إلى عمل مسرحي يتواصل خارج المهرجانات، ويوجد في الساحة حراكا يومياً معمماً على الفرق والمدن كافة" .المسرحي سلطان النيادي قال: "الأفخم من الشباب الإماراتيين الذين كرسوا جهداً كبيراً للثقافة والمسرح، ومن عادة ابن الإمارات أن يتميز إذا كرس جهده في اتجاه معين، نحن نبارك له ولأنفسنا هذا النجاح، ونعول عليه في عطاء أكبر وزيادة واتساع في الفعل المسرحي الإماراتي، وكذلك نأمل أن يقدم بصمة دولية على مستوى الهيئة التي يرأسها" .وقال حميد سمبيج: "هذا الفوز هو ثمرة جهد بذله الأفخ والعناصر المسرحية الإماراتية، من خلال عمله ومسؤولياته، وكذلك جهد الساحة المسرحية الإماراتية ككل، تلك الساحة التي هيأت الظروف لهذا الفوز من خلال السمعة الجيدة التي أصبح يحظى بها المسرح الإماراتي، نتيجة فعل مسرحي متميز ومستمر على مدى العام كان انطلاقه من الشارقة وعم اليوم جميع ربوع البلاد حتى أصبحت الإمارات عاصمة المسرح في الوطن العربي، بل عاصمة لنشاط ثقافي له أبعاد عربية وعالمية" .وأضاف سمبيج: نحن نفخر كثيراً بهذا الفوز، ونعتبره فوزاً للإمارات عامة، وهو فوز طبيعي ومستحق، لأن محمد الأفحم عمل بجهد واجتهاد وارتقى بمهرجان الفجيرة للمونودراما إلى أن أصبح فعلاً مسرحياً عالمياً، وأنا على يقين أن هذا الفوز سيثري الهيئة الدولية للمسرح بخبرة إماراتية جديدة .الفنان عبدالله زيد قال: "النجاح وليد المثابرة، ولن يصل إلى القمة من ظل قابعا في السفح، ومحمد الأفخم مثابر ومجتهد، وكل الوسط المسرحي الإماراتي مثابر ومجتهد، وهو مثال للشاب الإماراتي المفعم بالعطاء والحماسة للعمل، وليس غريباً على أبناء الإمارات الفوز واستحقاق المناصب العالية، نحن فخورون بأن يفوز أحد رجالنا المتميزين، وأن تتربع الإمارات على رئاسة هذه الهيئة المسرحية الدولية" .وقال د . هيثم الخواجه: "الحراك المسرحي في دولة الإمارات العربية المتحدة الذي بدأ منذ عقدين تقريباً حقق الكثير من النجاحات، سواء فيما يتعلق بكتابة النص المسرحي أو العرض المسرحي أو ما يمهد لذلك من ورش ومختبرات ومهرجانات، والذي جعل الحراك المسرحي متميزاً أيضاً هو البدء من المسرح المدرسي إلى مسرح الأطفال إلى الجامعي إلى الشباب إلى مسرح الكبار، هذه البنية المتكاملة جعلت الحركة المسرحية في الإمارات قابلة للتطور والنمو ما حقق الفوز في كثيرمن العروض والجوائز الكبيرة، ولا ريب أن صاحب السمو الشيخ الدكتور سلطان بن محمد القاسمي عضو المجلس الأعلى حاكم الشارقة، الذي قدم دعماً مادياً ومعنوياً وإبداعياً للمسرح أضاف الكثير إلى هذا الفن العظيم" .وأضاف الخواجة: كل ذلك أهّل الحركة المسرحية في الإمارات لأن تكون مضيئة بشكل حقيقي، وما رأيناه أن هذا الفوز جاء بشكل حقيقي، وما أراه أن هذا الفوز تستحقه دولة الإمارات بجدارة، طالما أن ما يحيط بها لم يصل إلى هذا المستوى من العطاء . \n\nأفكار:\n- المحتوى الرئيسي: فوز الإمارات برئاسة الهيئة الدولية للمسرح\n- الثيمة الرئيسية: الثقافة والفنون\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 10%|█         | 2/20 [00:10<01:36,  5.38s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nاستضاف مركز الشارقة لفن الخط العربي والزخرفة مساء أمس الأول معرض ( حرف ولون ) لأعمال منتسبي المركز التابع لمجمع الشارقة للآداب والفنون، بحضور هنا سيف السويدي رئيسة هيئة البيئة والمحميات الطبيعية وعضو المجلس التنفيذي، وهشام المظلوم رئيس المجمع.شارك في المعرض أربعون منتسباً للمركز، وبلغ عدد الأعمال 50 عملاً خطياً وفق خطوط وزخارف متنوعة ومختلفة في المدارس والاتجاهات، وتبدو في المعرض الذي يضم مجموعة من اللوحات الخطية قضية تأكيد الابتكار جلية بالرغم من الالتزام الواضح بميزان القواعد ونواظم كل نوع من الخطوط المستهدفة للتعبير عن التراكيب البصرية اللافتة للخط العربي الأصيل، ولوحظ أن المواضيع المطروحة متعددة بدءاً من الآيات الكريمة وانتهاء بتشكيل مجرد للأحرف، إلا أن اللون كما هو واضح في عنوان المعرض كان حاضراً في كثير من اللوحات في خطوة للتفرد ولتنويع الإيقاع، وكان لخط النسخ والديواني الجلي حضور واسع ومهم بين الخطوط والمعروضات. رافق المعرض ورشة «خط» أشرفت عليها مروة منذر، وطلال السباعي، وشارك فيها مجموعة من الحضور، حيث شاهدوا تطبيقاً عملياً لكتابة بعض العبارات والأسماء. \nأفكار:\n- المحتوى الرئيسي: معرض (حرف ولون) لأعمال منتسبي مركز الشارقة لفن الخط العربي والزخرفة\n- الثيمة الرئيسية: الثقافة والفنون\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة'}]


 الثقافة

 15%|█▌        | 3/20 [00:16<01:32,  5.47s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nباسمة يونس قد يبدو العنوان اسماً لرواية؛ لكنه الاسم الذي أطلقته جامعة كيس ويسترن ريزرف في ولاية كليفلاند على معهد أسسته عام 2001؛ للتوعية بأهمية الحب، الذي لا يحده شيء من خلال البحث في معنى هذا الحب، وكل عناصره المحيطة به. وتعرف هذه المؤسسة الحب في رسالتها على أنه الشعور الداخلي الذي يجعل من سعادة شخص آخر وطمأنينته واستقراره دافعاً للشعور بالسعادة، بما يعني أن من يسعد لسعادة شخص آخر فهو يحبه حباً حقيقياً ومطلقاً.وقد تأسست فكرة المعهد على قانون بسيط مفاده، أن الحب اللامحدود يقوم على قانون العطاء والسخاء دون انتظار مردود أو مقابل، وهو عنوان كتاب أصدره المعهد، وأصبح من الكتب الأكثر مبيعاً وعنوانه: «لماذا تحدث الأشياء الجيدة للناس الطيبين». ويتضمن الكتاب الكثير من القصص والحكم وما يختص بالجانب العلمي ومقياس التقييم الذاتي، وتمت ترجمته إلى أكثر من لغة، ولا يزال مقروءاً، وتتم مناقشته عبر العالم. ورغم وجود آلاف الكتب عن الحب؛ لكنها جميعها كانت تركز على تاريخ الأفكار المنطقية والفلسفية دون الأخذ بعين الاعتبار فكرة البحث العلمي من أجل فهم الحب اللامحدود بطريقة البحث التي تجمع بين علم الوراثة والجينات والعلوم الاجتماعية وعلم النفس الإيجابي، مع الأخذ في الاعتبار، الأفكار الدينية العظيمة والقيم الإنسانية، التي يجب الحفاظ عليها؛ كي لا يصبح مستقبل البشرية في حال غيابها في مواجهة خطر متزايد.الحب اللامحدود هو النقطة الأساسية والمهمة، التي يجب أن يلتقي عندها مستقبل البشرية، وهو الحب الذي يقدمه الإنسان لآخرين لم يقدموا له شيئاً؛ لكنه سيحث الناس على إعادة توجيه مشاعرهم العدائية بعيداً عن بعضهم بحيث يصبح كفاح البشر المشترك ضد الأمراض والمجاعات والفقر والعنف والاعتداءات الأخرى فقط.ويبحث المعهد، من خلال تحقيقات علمية مبتكرة على شكل حوارات تفاعلية تتبع النهج العلمي، عن نوعية الناس الذين يمنحون الآخرين بسخاء؛ ليعرف، عبر هذه الحوارات، إن كانوا يتمتعون بصحة أفضل من غيرهم، وهل يعيشون حياة أطول؟، هل يشفي الحب من الأمراض؟، هل يمكن القول إن الكرم والتعاون يجعلان الإنسان، الذي يسلكهما أكثر صحة من الآخر الذي يغلب عليه طبع الأنانية وحب الذات؟، ما الذي يمكننا أن نكتشفه من خلال البحث في حيوات الأفراد المحبين للآخرين؟إن فكرة المعهد تقوم على أهمية تعليم الأجيال القادمة معنى وطريقة العيش بسلام، وكيف يصبح العطاء قانوناً في حياتهم من أجل حب بلا حدود. basema.younes@gmail.com \nأفكار:\n- المحتوى الرئيسي: تأسيس معهد الحب اللامحدود في جامعة كيس ويسترن ريزرف\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين '}]


 الدين

 20%|██        | 4/20 [00:21<01:26,  5.42s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nأبوظبي: «الخليج» أكد عدد من الخبراء والمسؤولين المشاركين في فعاليات جناح جائزة خليفة التربوية أن المعرض أصبح علامة بارزة في مسيرة الفكر والثقافة، وترجم المكانة المرموقة التي تحظى بها أبوظبي كمركز عالمي للإبداع الفكري والإشعاع الحضاري.وشهد جناح الجائزة عدداً من المحاضرات الثقافية وورش العمل التطبيقية التي ترسخ ثقافة التميز لدى مختلف فئات المجتمع.وقالت أمل العفيفي الأمين العام للجائزة: إن البرنامج الثقافي للجائزة شمل محاضرة بعنوان «ثقافة التميز» تحدث فيها الدكتور خالد العبري عضو اللجنة التنفيذية للجائزة حول مسيرة الجائزة منذ انطلاقها في العام 2007 لتشكل بذلك مبادرة وطنية رائدة لغرس ثقافة التميز في الميدان التربوي وتحفيز المعلمين والقيادات التعليمية والأكاديمية بل ومختلف فئات المجتمع على الإبداع، وهو ما تحقق لها بامتياز وجدارة.كما تحدث محمد سالم الظاهري مستشار رئيس دائرة التعليم والمعرفة في امارة أبوظبي في محاضرة بعنوان «زايد والتعليم» عن فكر ورؤية هذا القائد العظيم الذي جعل من التعليم ركيزة أساسية للنهضة الحضارية التي نشهدها، والتي تعتبر نموذجاً يحتذى به إقليمياً ودولياً.وقال الظاهري: عندما نتحدث عن المغفور له الشيخ زايد بن سلطان آل نهيان «طيب الله ثراه» فإننا نقف أمام أحد قادة العالم الذين سطروا بفكرهم ورؤيتهم إنجازات حضارية تفخر بها البشرية، واليوم فإنني في هذه المحاضرة أسلط الضوء فقط على محاور بسيطة تترجم فكر ورؤية القائد المؤسس «طيب الله ثراه». وتابع: أدرك «الشيخ زايد» أنه بدون تعليم أبناء وبنات الوطن فلن تتحقق النهضة المنشودة، ومن هنا وجه «الشيخ زايد» ببناء منظومة من المدارس والمعاهد التعليمية في مختلف مناطق إمارة أبوظبي، فكانت هناك مدارس في المدن والقرى، والتجمعات السكنية في مختلف أرجاء الإمارة.وقدم كل من الدكتور محمد مصطفى أحمد من جامعة الإمارات وعائشة الزعابي من روضة الغدير بمنطقة رأس الخيمة التعليمية ورشة عمل حول «ثقافة التميز»، عرض فيها كل منهما الآليات التي قادتهما لحصد جائزة خليفة التربوية عن فئة الأستاذ الجامعي المتميز في البحث العلمي، وفئة الأداء التعليمي المؤسسي. \nأفكار:\n- المحتوى الرئيسي: فعاليات جناح جائزة خليفة التربوية\n- الثيمة الرئيسية: الثقافة والتعليم\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 25%|██▌       | 5/20 [00:26<01:20,  5.34s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nيمكن القول باطمئنان أن شهر رمضان المبارك هو شهر فن الخط العربي، ففي هذا الشهر الكريم تكثر مهرجانات ومعارض الخط في الكثير من البلدان العربية وربما الإسلامية أيضاً، وذلك لاقتران الخط العربي بدلالات دينية روحية إلى جانب سماته الجمالية التي تعلّق بها فنانون تشكيليون غير عرب رأوا في الخط طاقة إبداعية متميزة عن كل خطوط الأبجديات الحية في العالم.لكن رمضان في الإمارات من حيث حجم هذه المعارض يختلف عن أي بلد عربي آخر، فخلال هذا الشهر تنشط وتتفاعل البرامج اليومية المتعلقة بمهرجان الفنون الإسلامية والذي يتميز بأنه (أي المهرجان) فعالية طويلة تستمر الى شهر وأكثر، وحقيقة الأمر أن المهرجان هو مجموعة مهرجانات إذا اعتبرنا أن سلسلة طويلة من معارض الخط تقام في فترة محددة من العام هي في حقيقتها مهرجانات خطيّة أو خطوطية. فكل معرض له شخصيته وأساليبه الفنية ورؤاه الفكرية والجمالية.المرئي والمسموع على سبيل المثال له صورة حروفية تشكيلية أو صورة خطية تجعل منه فعالية لها وزنها الخاص على أجندات المهرجان.وفي هذه الدورة من مهرجان الفنون الإسلامية لا بد أن نلتفت بقوة الى الخطاطات العربيات اللواتي جئن من شمال إفريقيا ليعرضن للمرة الأولى هنا في الشارقة موئل فن الخط العربي وعاصمة الكتاب والمسرح.هناك أيضاً معرض دروب الحروف.. وهو الآخر فضاء خطّي يمثل.. تجوالاً بصرياً يتماوج مع المعاني السامية للنصوص المختارة، كما يعبّر عن فضاءات الخط العربي ذات الخصوصية المغاربية.. كما جاء في تعريف هذا المعرض المهرجان في كتيبات دائرة الثقافة والإعلام في الشارقة.ولا ننسى تلك الروح العربية الأصيلة المبثوثة في أعمال معرض جوانيات للفنان راشد النقبي، وكذلك معرض همسات فاس للفنان جاسم ربيع، وأيضاً معرض نداء المآذن.. .. بوح ملاصق للروح، مسهب في تعرية الذات من دنس الدنيا وركامها.... إلخ.إذن.. معارض تلو معارض، أو مجموعة مهرجانات عرض في مهرجان واحد عنوانه العريض فلك الفسيفساء يميّز الشارقة ويجعلها بكل جدارة المكان المثالي لنمو وتنمية فن الخط العربي بكل أبعاده الروحية والتشكيلية والجمالية.ولا تتوقف عجلة الخط العربي عند مهرجان فلك الفسيفساء، بل يلتقي في الإمارات 30 خطاطاً في تقليد سنوي أطلقته وزارة الثقافة والشباب وتنمية المجتمع لكتابة نسخة واحدة من القرآن الكريم، وفي دبي يعرض اليوم 29 فناناً تجارب خطية ذات اجتهادات تجريدية تؤشر على الطاقة الإبداعية الظاهرة والباطنة في انسياب الخط العربي.الإمارات من أبرز البلدان العربية وغير العربية التي تعطي فن الخط كل هذا الاهتمام وكل هذه العناية الثقافية في إطار توجه ثقافي شامل تفخر به البلاد وتعتز. \nأفكار:\n- المحتوى الرئيسي: شهر رمضان ومهرجانات الخط العربي في الإمارات\n- الثيمة الرئيسية: الثقافة والفنون\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 30%|███       | 6/20 [00:32<01:17,  5.54s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nيشارك المسرحي الشاب رامي مجدي في مهرجان الشارقة للمسرحيات القصيرة بعرض الواشي لبريخت في ثاني تجربة إخراجية، بعد أن أخرج في الدورة الأولى من المهرجان مسرحية الغرباء لا يشربون القهوة التي قدمته موهبة إخراجية يعوّل عليها في المستقبل، ويقول مجدي عن هذه المشاركة: لقد كانت تجربتي في إخراج (الغرباء لا يشربون القهوة) مفيدة جداً وتعرفت من خلالها إلى كثير من خفايا العملية الإخراجية، خصوصاً طرق التعامل مع النص، وأساليب قيادة الفريق وتوجيه الممثلين وغيرها، وقد كان الانطباع العام لدى النقاد خلال المهرجان أن العمل جيد، ورغم أن العرض استبعد من الجائزة لأنه تجاوز الوقت المحدد للمسرحيات القصيرة، إلا أن تلك التجربة أفادتني كثيراً، وشجعتني على مواصلة المغامرة الإخراجية في هذا العمل الجديد، وقد اخترت نصاً لواحد من أعمدة المسرح العالمي وقائد مدرسة التجريب فيه .وعن مضمون العرض الجديد يقول مجدي: النص مكتوب سنة ،1938 قبل أن يتجه بريخت اتجاهه التجريبي، فهو يمكن أن يصنّف في باب المرحلة الواقعية لهذا الكاتب، لكنني خلال العرض أحاول أن أضفي عليه نوعاً من التجريب، كما أعمد إلى إعطائه صبغة كوميدية عن طريق التناقض في المواقف والمبالغة في الأداء، وهو يتناول حياة أسرة ألمانية تتألف من أب وأم وطفل وخادمة، ويصوّر الكم الهائل من الرعب الذي كان يسيطر على المجتمع أثناء الفترة النازية، فقد كان محرماً على الفرد العادي الكلام في السياسة، وكان المخبرون مبثوثين في كل مكان، وفي إحدى المرات يتكلم الأب سهواً بألفاظ سيئة عن هتلر في حضور الطفل، ثم يكتشف خطأه ويعيش فترات رعب خوفاً من أن يتكلم الطفل بتلك الألفاظ أمام الغير فيصل الأمر إلى مخبري هتلر، ما يجعل الأب يعيش حالة من حالات الهلوسة .يشارك في التمثيل في الواشي هاني الطمباري، ودنيا، وأنس عبدالله، وولاء حامد، وعمر الفاروق، ويشرف على تدريبات المهرجان الفنان يحيى الحاج، كما يشارك رامي مجدي كممثل في عرض آخر من عروض المهرجان هو حديقة الحيوان للكاتب الإنجليزي إدوارد ألبي، وهو من إخراج ماهر مزوق .يدين رامي مجدي الذي يحمل شهادة في الفلسفة وعلم النفس بكثير من تجاربه المسرحية لإدارة المسرح في دائرة الثقافة والإعلام في الشارقة التي فتحت له باب التمثيل عن طريق الورش التي نظمتها خلال السنوات الماضية، وكان من نتائجها إنشاء فرقة مسرحية تابعة للدائرة كان رامي أحد أعضائها المتميزين، ويقول عن ذلك: كانت لي تجارب سابقة في مجال المسرح أثناء فترة الدراسة الجامعية، لكنها لم تكن مؤسسة بسبب عدم وجود الدعم التدريبي، لكنني وجدت في البرامج التدريبية والورش التي تقيمها دائرة الثقافة والإعلام ضالتي، فكنت حاضراً فيها باستمرار، وقد فتحت لي الباب واسعاً للتمثيل وفنون المسرح بشكل عام، وانتميت إلى فرقة المسرح التابعة للدائرة وشاركت معها في كثير من العروض تحت إشراف الفنان الرشيد أحمد عيسى، كما كانت الورشة المتكاملة التي تقيمها إدارة المسرح قبل مهرجان المسرحيات القصيرة مناسبة للاحتكاك بعدد من كبار المسرحيين العرب الذين قدموا لنا تجاربهم المختلفة خلال الدورتين السابقتين، مثل خالد جلال، وجان داوود، وإبراهيم سالم، ويحيى الحاج، وهي خبرات تلخص تجارب المدارس المسرحية العربية على اختلافها وهو تنوع من النادر أن يحصل عليه دارسو المسرح، لأن الأكاديميات تقدم تجارب بلد واحد، وهو ما يعطينا قدرة على التعامل مع مختلف المدارس والاستفادة منها . \n\nأفكار:\n- المحتوى الرئيسي: مشاركة رامي مجدي في مهرجان الشارقة للمسرحيات القصيرة\n- الثيمة الرئيسية: المسرح والفنون الأدائية\n- الفئة الأنسب: الفنون والثقافة\n\nالفئة المتوقعة: الفنون والثقافة\n\nالفئة'}]


 الفنون والثقافة

الفئة

 35%|███▌      | 7/20 [00:38<01:12,  5.57s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nأبوظبي: نجاة الفارسنظم اتحاد كتاب وأدباء الإمارات فرع أبوظبي في مقره بالمسرح الوطني أمس الأول، محاضرة بعنوان «الكتابة الساخرة.. وشائج مع الصحافة المحلية» قدمت إطلالة على تجربة الإعلامي والكاتب الساخر الأردني عبد الله شاهين، صاحب مدونة «أبو طراوة»، حاورته الإعلامية فاتن حمودي، بحضور حبيب الصايغ الأمين العام للاتحاد العام للأدباء والكتاب العرب، رئيس مجلس إدارة اتحاد كتاب وأدباء الإمارات، والعميد الدكتور صلاح عبيد الغول مدير مكتب احترام ثقافة القانون في وزارة الداخلية وعدد من الكتاب والأدباء.وأشارت فاتن حمودي إلى أن تواجد عبد الله شاهين يفرض حضور الابتسامة دائما، فمن يعرفه، يدرك أنه لا يريد مغادرة الطفولة المتبقية فيه، فهو رجل يأخذ في لحظات العالم نحو العدم ناسفا عرض الحائط بكل شيء. وألقى شاهين الضوء على تجربته، مشيرا إلى أن الكتابة الساخرة فيها صنعة أكثر من الموهبة، وهي مسألة يتعلمها الكاتب يوميا، موضحا أن الكتابة الساخرة بدأت في مصر وكان معظم الكتاب يوقعون كتاباتهم بأسماء مستعارة للتحايل على السلطة السياسية.وقدم حبيب الصايغ مداخلة أوضح فيها كيف تكتب الصحافة الخبر الطريف في المنوعات، رغم أن مضمونه مأساوي مثل «غرق طفل في سطل ماء» أو «زوجة تقطع زوجها إربا» وما شابه ذلك من أخبار. مضيفا أن الكتابة الساخرة أهم ما فيها العفوية والتلقائية بعيدا عن التصنع، وليس بالضرورة أن تكون الكتابة الساخرة مثيرة للضحك. واختتمت الأمسية بوَصلة موسيقية، عزف فيها عبد الله شاهين على الناي ورافقه على العود الفنان محمد عبد الرحيم.\nأفكار:\n- المحتوى الرئيسي: محاضرة حول الكتابة الساخرة وتجربة الإعلامي عبد الله شاهين\n- الثيمة الرئيسية: الثقافة والفنون\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 40%|████      | 8/20 [00:43<01:05,  5.47s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nالقاهرة «الخليج»: توفي مساء أمس الأول الروائي والناقد المصري علاء الديب أحد صناع فيلم (المومياء) الذي أخرجه شادي عبدالسلام في 1969 ومازال يأتي في صدارة الأفلام في استفتاءات النقاد لأفضل 100 فيلم عربي.ولد علاء الدين حب الله الديب في القاهرة عام 1939 وكان شقيقه الأكبر هو الروائي والناقد بدر الديب (1926-2005) الذي أسهم في التكوين الثقافي لأخيه علاء.وكان (عصير الكتب) من أشهر الأبواب في الصحافة الثقافية ويراه كثيرون سجلاً وإضاءات على مئات الكتب والروايات والمجموعات القصصية خلال بضعة عقود.بدأ الديب حياته الأدبية كاتباً للقصة القصيرة وصدرت مجموعته الأولى (القاهرة) عام 1964 وتلتها (صباح الجمعة) عام 1970 و(المسافر الأبدي) عام 1999. وله أيضاً خمس روايات هي (زهر الليمون) عام 1987 و(أطفال بلا دموع) عام 1989 و(قمر على المستنقع) عام 1993 و(عيون البنفسج) عام 1999 و(أيام وردية) عام 2000، وله أعمال مترجمة منها مسرحية (لعبة النهاية) لصموئيل بيكيت عام 1961. \nأفكار:\n- المحتوى الرئيسي: وفاة الروائي والناقد المصري علاء الديب\n- الثيمة الرئيسية: الثقافة\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 45%|████▌     | 9/20 [00:48<00:58,  5.33s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nتبدو مسألة النشر بكل معطياتها ومفاصلها في الوطن العربي متأخرة عن مثيلاتها في البلدان الأوروبية، وهو ما ينعكس في مؤشرات عدة في عالم النشر العربي، ومن بين تلك المؤشرات انخفاض عدد النسخ المطبوعة من العنوان الواحد، وصعوبة التوزيع، وقضايا الرقابة، ونسبة الأمية التي ما زالت مسيطرة على بعض المجتمعات، إضافة إلى مسائل أخرى، وفي مقدمتها انخفاض جودة العمل المؤسساتي النشري الذي يفتقد إلى آليات حديثة في التعاطي مع الترويج للكتاب، إضافة إلى ارتفاع سعر الكتاب نفسه قياساً إلى دخل الفرد في غير بلد عربي، وكل هذه المسائل قد انعكست سلباً على عمل الكاتب نفسه، ونقصد هنا الكاتب الاحترافي الذي من المفترض أن يعيش مادياً من وراء إبداعاته الفكرية أو الإبداعية أو الثقافية .لا يخفى على أحد أن آخر ما يفكر فيه الكاتب العربي هو أن يعيش من وراء ما يكتب، حتى إنه لا يعرف تماماً كم وزّع الناشر من نسخ كتابه، وفي معظم الأحيان يكون على الكاتب أن يدفع للناشر تكاليف النشر، لكن واقع هذه الحال مختلف كلياً في كل تفصيلاته في أوروبا وأمريكا الشمالية وأمريكا اللاتينية، خاصة أن مهنة النشر راحت تتطور كثيراً في السنوات الأخيرة، وما زالت واحدة من المهن التي تدر أرباحاً كبيرة على صاحبها، وهو ما ينعكس بالضرورة على الكتّاب أنفسهم، وعلى قدرتهم على العيش الكريم من نتاجاتهم الإبداعية، واكتساب الشهرة التي لاتقل عن شهرة نجوم السينما في بعض الأحيان، خاصة أن الكثير من الشركات المنتجة للأفلام تقوم بتحويل القصص والروايات والكتب الوثائقية إلى أفلام، ويكون لمؤلف العمل الأصلي نصيب في كعكة الأرباح الكبيرة التي تحققها تلك الأفلام .وفي السياق نفسه، فقد تنامت في أوروبا وأمريكا مهنة الوسيط الأدبي، ومهمة هذا الوسيط تتمثل في التفاوض عوضاً عن الكاتب مع دور النشر، وتأمين أفضل شروط للنشر، وأفضل عائدات ممكنة للكاتب، وتوسيع آفاق استثمار العمل الأدبي أو الفكري، مثل تحويل عمل الروائيين إلى أفلام، وعقد صفقات لترجمة الكتاب، والاتفاق مع جهات ثقافية لتنظيم ندوات للكاتب من أجل اللقاء مع الجمهور، وإيجاد ناشر إلكتروني يقوم بتوزيع الكتاب إلكترونياً عبر العالم، وقد أصبح هناك الكثير من المؤسسات المرموقة في هذا المجال، بينما يحجم الكثير من المبدعين العرب عن إصدار أعمالهم نتيجة إحساسهم العميق باللاجدوى، وذلك في ظل عدم وجود ثقة لدى الكاتب بقدرة المسؤولين عن النشر على تأمين أفضل شروط للترويج المطلوب للكتاب، خاصة أن الكثير من دور النشر العربية لا تزيد على كونها دكاكين صغيرة، يعتاش أصحابها على ما يدفعه الكاتب لنشر كتابه، وليس لديهم نظام مؤسساتي قادر على توسيع آفاق النشر، وإبرام عقود ترجمة مع دور نشر عالمية من أجل ترجمة أعمال الكتاب العرب إلى مختلف اللغات، وهو الأمر الذي من شأنه أن يدر أموالاً جيدة على الدار نفسها، وعلى الكاتب، ما يسمح له بالتفرغ مع الوقت لإبداعه، وأن يكون سفيراً حقيقياً للثقافة العربية، وما تنتجه من إبداعات .هل نحن اليوم بحاجة إلى مهن تدعم الكاتب؟ ومنها الوسيط الأدبي، حيث يخفف هذا الوسيط على الكاتب عبء التفاوض مع دور النشر، وتكون لديه مهام متعددة تخدم عمل الكاتب، حيث يتابع له عائدات كتبه، و يكون لديه الدافع القوي لتوسيع دائرة تسويق الكتاب، وهو منفعته المادية المباشرة، وربما يعترض كثيرون على هذا المبدأ، أو على هذه المهنة، لكن الواقع الموضوعي يشير إلى أن هذه المهنة أصبحت جزءاً لا يتجزأ من مهنة النشر نفسها في غير بلد عالمي، وقد اجتاحت دولاً أوروبية عدة، مثل بريطانيا، وإسبانيا، وفرنسا، وألمانيا، والدانمارك، إضافة طبعاً إلى أمريكا، واليوم يتمتع الكثير من الكتّاب بوضع مادي ومعنوي يسمح لهم بأن يأخذوا موقعهم الذي يستحقونه مبدعين، وهو ما يطمح إليه- بكل تأكيد- كل كاتب، خاصة الكاتب العربي . \n\nأفكار:\n- المحتوى الرئيسي: تحديات النشر في العالم العربي\n- الثيمة الرئيسية: الثقافة\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 50%|█████     | 10/20 [00:54<00:53,  5.34s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nنظم النادي الإيراني في دبي مساء أمس الأول على هامش المهرجان امسية شعرية، استضاف فيها كلاً من الشاعرين الايرانيين موسوي جارمارودي، ود. محمد الحاتمي الذي قدم في البداية تمهيداً تاريخياً عن الشعر العربي والفارسي أكد فيه أن الشعر يعبر عن مكونات الهوية الوطنية ووجدان البشر.ولفت الحاتمي الانتباه إلى أن القرن الذي نعيشه يشهد تراجعاً للشعر بسبب ضعف مستوى تعليم اللغة العربية. ثم القى بعد ذلك مجموعة من قصائده، التي عبرت عن الجرائم الوحشية للكيان الصهيوني.ثم ألقى موسوي جارمارودي قصيدته التجلي التي صور فيها حبه الشديد للحياة وتمسكه بها.وفي السياق نفسه نظم النادي السوداني أمسية شعرية استضاف فيها كلاً من د. علي جعفر العلاق العراق وروضة الحاج السودان وتطرقت قصائدهما أيضاً إلى الهم القومي والذاتي.في البداية ألقى د. على جعفر العلاق مجموعة من قصائده: كيف انطفأنا، حرس لنوم الحبيبة، الرحيل، المجنون، صبر الوحشة، عناقيد بابلية، افتراض أصحيح ما يقول الشجر، أرض من الأضداد، واختتمها بقصيدة كلكامش، وهي قصائد تصور محنة العراق وقد استخدم الشاعر في هذه القصائد تيمات مستوحاة من الأساطير الآشورية والبابلية وظفها للتعبير عن الواقع الذي يعيشه العراق والعالم العربي.وألقت روضة الحاج مجموعة من قصائدها مثل أحزان مآسينا وحقول الماء، وبلاغ امرأة عربية، وتمائم الغياب، وهي قصائد عبرت أيضاً عن الهم القومي والسوداني، محاولة أن تكون لسان حال المرأة، خصوصاً في قصيدة إمرأة مثل كل النساء.\nأفكار:\n- المحتوى الرئيسي: أمسية شعرية في النادي الإيراني والسوداني\n- الثيمة الرئيسية: الثقافة\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 55%|█████▌    | 11/20 [00:59<00:47,  5.32s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nمنذ أن بدأ الإدراك البشري، كان لا بد له من وسيلة للتعبير، وبتطور الكلام، الذي هو أول وسيلة من وسائل التخاطب، بدأ الإنسان أولى محطات تفاعله مع محيطه أولاً، ومن ثم مع الآخر، بهدف الحفاظ على كينونته، وترتيب وجوده، وتنسيق معالم تفاعله مع الآخرين وكافة عناصر البيئة من حوله . من هنا، كانت اللغة أول وسيط معرفي، يحتضن مشاعر الإنسان، ويخفف من تعبه في متاهة الكتلة المادية، التي تتألف من الصخر والبحر والطبيعة من حوله .هكذا تطور الكلام ليعكس ثقافة الشعوب ويمنحها فرصة الترويج لمشروعها الحياتي والفلسفي، وكان الشعر - إذا جاز التعبير- هو أول مختبر حياتي يبرمج اللغة العصبية للبشر الحالمين بالحرية والعدل والمساواة .هل يمكن المجازفة والادعاء بأن الشعر، وانطلاقاً من هذه الأهمية، هو ابن الفطرة، وبوصلة الاستدلال على الكينونة، ومختبر الطاقة الإنسانية، وأول صمام أمان ضد الخشية والمجهول؟وبهذا المعنى أيضاً، ألا يمكن اعتبار الشعر، هو أول صرخة حقيقية في وجه الصمت، وأول منبه عصبي، يلفت النظر الى ضرورة تفسير الأشياء والجمادات من حولنا؟وفي العصر الراهن، حين تمت مقارنته مع الصورة المبهرة التي جاءت مع تطور وسائل الاتصال، وبروز فنون السينما والفيديو والشاشات العملاقة، والخشية من فقدان دوره، استطاع الشعر أن يعيد الاعتبار لنفسه، لتزداد هيبة اللغة من خلاله، وليصبح للأشياء دور في تفسير الظواهر الحياتية بكل صخبها وألغازها وإشاراتها، وكان هو نفسه، أول دالة منطقية لتفسير غوامض الصورة ومحاولة تفسير عوالم الأحجية .لقد قدم الجاحظ أول تفسير متقدم للشعر، تجاوز اختزاله في النظم البياني الذي يصور دخائل النفس فقط، الى اعتباره نظاماً لغوياً خاصاً، لا بد له أن يقدم قيمة ما، وليشير بوضوح الى مفهوم الصناعة التي تقف على المادة المطروحة في الطريق وضرورة استخدام أدوات مخصوصة قادرة على إعادة تفسير الأشياء وفق تآلفها الصوتي والدلالي، وهناك كثير من النماذج الشعرية العالمية التي طرحت جدلية اللغة والأشياء، مثل الشاعر الفرنسي غيللفك الذي وصف بشاعر الأشياء .يقول أدونيس في التعريف بهذا الشاعر إذا كانت غنائية غيللفك اختراقاً لصمت الأشياء، فما يكون الشعر في هذا المستوى؟ الشعر نحت للصمت: يجيب الشاعر متابعاً - كما ندخل النطق في الشيء، يجب أن ندخل الصمت في الكلمة . ويضيف أن إدخال الصمت في الكلام، هو بالضبط ما يميز الشعر، إزاء النثر . إنما الصعوبة الكبرى هي في جعل الصمت يسمع ويحس، غيللفك في شعره كله، نحات للصمت .إن الأشياء هي مادة الشعر الرئيسية، أما الطبيعة فهي الحاضنة التي تتسع لأفعال الناس وحركاتهم، ومألوف حيواتهم اليومية، أما الشاعر فهو صفصافة الأشياء ومنفذ حركيتها ومرتب علاقة الإنسان بها، في شعاع إنساني مدهش ومتقد . \n\nأفكار:\n- المحتوى الرئيسي: دور الشعر في تفسير الظواهر الحياتية والثقافة\n- الثيمة الرئيسية: الثقافة والأدب\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 60%|██████    | 12/20 [01:03<00:40,  5.11s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nضمن سلسلة ثلاثاء السوربون لجامعة باريس - السوربون أبوظبي، عقدت الجامعة في المجمع الثقافي أمس الأول محاضرة في المجمع الثقافي تحت عنوان بونابرت: فرنسا ومصر 1797 - 1799 ألقاها الأستاذ الجامعي جيرود بوماريد، أستاذ التاريخ والحضارات في سوربون أبوظبي.بدأ بوماريد محاضرته بسرد تاريخ الحملة الفرنسية في عام 1798 واصفاً إياها بأنها الحملة الأولى منذ الحملتين الصليبيتين على مصر، وأضاف: من المشوق أن نتحرى عن أهداف اهتمام دولة بأخرى. يمكننا تلخيص أهداف الحملة الفرنسية الى ثلاثة أهداف سياسية تتمثل في موقع مصر الاستراتيجي وتوق نابليون بونابرت للتعرف الى الإسلام وامبيرالية بونابرت وحلمه بجعل مصر جزءاً من فرنسا، هو ما فشل في تحقيقه. ولدى جيرود بوماريد كتب عدة تُعنى بدراسة الشرق، منها كتاب عن العصر العثماني. \n\nأفكار:\n- المحتوى الرئيسي: محاضرة عن الحملة الفرنسية في مصر\n- الثيمة الرئيسية: التاريخ\n- الفئة الأنسب: التاريخ\n\nالفئة المتوقعة: التاريخ '}]


 التاريخ

 65%|██████▌   | 13/20 [01:09<00:36,  5.21s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nتقيم الفنانة ليتا كابيلوت معرضاً في مطلع العام المقبل في دبي، ويضم المعرض 35 لوحة، تركز خلالها على الوجوه .كابيلوت ولدت في العام 1961 في مجتمع غجري، لأم هجرتها قبل أن تتجاوز الثلاثة شهور من عمرها، لتتكفل جدتها الغجرية بتربيتها إلى سن الثامنة من عمرها، بعدما منعتها من الالتحاق بالمدرسة، إلا أن تسليمها في مابعد إلى أحد المياتم من قبل جدتها، شكل نقطة تحول بارزة في حياتها، لتتدرج رويداً رويداً في عالم الفن، بعد نضوج واكتشاف موهبتها، .ومن أبرز ما لاحظه النقاد حول أعمال ليتا كابيلوت أن أعمالها الفنية استطاعت أن تخلق عالماً أكبر من الصورة الفنية، حيث الوحة في هيئة كائن يتآلف من الألوان الزيتية والجبس والقماش، لتستطيع إثارة الجدل بحق من خلال استفزازها للخيال وهي تلتقط عوالم فتيات الشوارع والغانيات والمهرجين والموسيقيين، وقد جمعت كل ذلك في كتاب صدر عن دار فريدا كاهلو، كي تعد نفسها في تناول مشروعها المهم الذي تسميه أم المآسي الإنسانية، حيث تسلط خلاله الضوء على المرض العقلي محور تجربتها الجديدة، ضمن أسلوبها الذي يعتمد على الأبيض والأسود وتفلسفهما على نحو خاص . \nأفكار:\n- المحتوى الرئيسي: معرض فني للفنانة ليتا كابيلوت\n- الثيمة الرئيسية: الفن والثقافة\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 70%|███████   | 14/20 [01:14<00:31,  5.33s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nأبوظبي: «الخليج» تأهل في حلقة، أمس الأول، من برنامج «شاعر المليون» السعودي متعب الشراري، والإماراتي علي سالم الهاملي، حيث حصل الشراري على أعلى درجات تصويت الجمهور التي وصلت إلى 66%، وحصل الهاملي على 57%، لينتقلا بذلك إلى المرحلة الثانية من البرنامج، أما العماني حسن المعمري فتأهل ببطاقة لجنة التحكيم وحصل على 49 درجة. حضر الحلقة الدكتور علي بن تميم، مدير عام شركة أبوظبي للإعلام، وعيسى سيف المزروعي، نائب رئيس لجنة إدارة المهرجانات والبرامج الثقافية والتراثية، و بدر صفوق، وتركي المريخي. شارك في الحلقة الشعراء ياسر الزلباني من الأردن، حسن علي المعمري، حمد الجودان العازمي من الكويت، راشد بن قطيما وعكّاش العتيبي من السعودية، وسالم بن كدح الراشدي من الإمارات. وقرأوا باقة قصائد انحاز أكثرها نحو الوطن، وغلب عليها الفخر والمجد بالجنود الأبطال الذين يقاتلون في اليمن الشقيق. وتضمنت الحلقة تقريرين موضوعهما التراث والبيئة، أولهما تقرير استعاد أقوالاً للمغفور له، بإذن الله، الشيخ زايد بن سلطان آل نهيان، عن التراث، ودعوته للتمسك به والحفاظ عليه، خاصة أنه يعتبر جزءاً أساسياً في تاريخ دولة الإمارات. واستضافت الحلقة الشاعرة زينب البلوشي، التي أطلق عليها الإعلامي حمد السعيد لقب «شيهانة الشعر». وبحديثها عن الألقاب؛ قالت إنها إضافة جميلة في مسيرة أي شاعر، لكن يبقى الشعر وما يقدمه الشاعر من إبداع هو الأهم. وفي ردها على سؤال حسين العامري حول الدعم الذي تحصل عليه الشاعرات الإماراتيات، أكدت أن جميع الجهات المعنية تمنح الدعم للشاعرات، غير أن المطلوب منهن الإبداع في نتاجهن الشعري. وهنأت البلوشي قيادة دولة الإمارات بسلامة الشيخ زايد بن حمدان بن زايد آل نهيان، وبعودته إلى الوطن، ورحبت به في أول قصيدة ألقتها، وقالت: يا مرحبا بك يا سميّ ابوي زايد مرحبا كنّك من الجنة تزفّ الحق ويردّ الصدا والله ما من شر دام أمثالك لهذا الوطن عند اللزم؛ تارد حياض الموت وترد العدا رد الخبر طيّب حفيده العود ما عوّد خلي من دون أمن اليار لا رد البلاد ولا هدا للأرض للإنسان للتاريخ للحق ونِعم تتأصل بنا تربية زايد ولا راحت سدى \nأفكار:\n- المحتوى الرئيسي: حلقة من برنامج «شاعر المليون»\n- الثيمة الرئيسية: الثقافة والفنون\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 75%|███████▌  | 15/20 [01:20<00:26,  5.28s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nأنشئت الهيئة العربية للمسرح في 28 أكتوبر 2007 بمبادرة من صاحب السمو الشيخ الدكتور سلطان بن محمد القاسمي عضو المجلس الأعلى للاتحاد حاكم الشارقة، وهي هيئة غير حكومية وغير ربحية تهتم بقضايا المسرح العربي وتواكب مستجداته من خلال مندوبيها في العديد من العواصم العربية . وتتخذ الهيئة من الشارقة مقرًا لها، ومن ضمن الأهداف الرئيسة التي تسعى إلى إنجازها النهوض بالعمل المسرحي العربي، وترسيخ الثقافة المسرحية، وإشهار الأعمال المسرحية الشابة، ودعمها وتبادل الخبرات والانفتاح على مختلف التجارب في فن الخشبة . حول آفاق عمل الهيئة في الخارج وإسهامها في النهوض بالمسرح العربي يقول غنام غنام المنسق الإعلامي للهيئة العربية للمسرح الهيئة تسعى بجهود حثيثة إلى التواصل والتنسيق مع مختلف الفاعلين المسرحيين في الوطن العربي، وذلك من خلال مندوبيها الذين يصل عددهم إلى 20 مندوبا يعملون على التنسيق مع الجهات المختصة في كل دولة في إطار شراكة حقيقية . ويضيف غنام: تعمل الهيئة على رعاية ودعم التظاهرات الثقافية والفعاليات المسرحية على مستوى الوطن العربي، من خلال مهرجان المسرح العربي السنوي، الذي نظمته في العديد من العواصم العربية في مصر وتونس ولبنان والأردن، كما سيتم تنظيم دورته المقبلة في إحدى دول الخليج، وتعد فكرة هذا المهرجان الكبير نابعةً من الهيئة، وهي كذلك الممولة والمنظمة لمختلف فعالياته . في إطار أنشطتها في الخارج يقول غنام نظمنا منذ فترة وجيزة ندوة تحت عنوان نقد التجربة . .همزة وصل في المغرب بالتعاون مع مهرجان المسرح الوطني في مكناس وسنعمل على تعميم مثل هذه الندوات ونشرها في مختلف البلدان العربية في غضون سنتين، كما نقيم الآن ورشة تأهيلية لمسرحيات شابات في لبنان، عن دور المرأة العربية وحضورها في المسرح بالتعاون مع نقابة المسرحيين، إضافة إلى ندوة فكرية في تونس بالتعاون مع مندوبنا هناك، وذلك ضمن فعاليات الاسطنبولي بالمنستير .ويقول بلال البدور الوكيل المساعد لشؤون الثقافة والفنون في وزارة الثقافة والشباب وتنمية المجتمع أي برنامج يندرج في إطار المسرح يجب علينا أن نتبناه وندعمه، لذلك تبنت الوزارة فكرة وجود مندوبين للهيئة العربية للمسرح في العواصم العربية، ودعت الوزارة أمين الهيئة العام لتطبيق الفكرة، وهو أمر ينم عن قناعة راسخة لامتداد التجربة المسرحية العربية وتفاعل بعضها مع بعض، لكنه يبقى مرهونا بتفعيل دور هؤلاء المندوبين وتنسيقهم مع الهيئة والجهات المختصة في البلدان العربية . ويرى البدور أن الوضع السياسي الراهن في الوطن العربي قد أسهم في إعاقة الكثير من النشاطات الثقافة والمسرحية على وجه الخصوص، ووضع مشاريعها قيد التنفيذ . ويلاحظ المسرحي خلفان علي الدرمكي أن الهيئة بدأت تنتشر خلال الآونة الأخيرة في العديد من البلدان العربية من خلال نشاطاتها والفعاليات التي تنظمها هنا أو هناك، وقد أسهم ذلك في الاطلاع على مختلف التجارب المسرحية العربية وتبادل الخبرات بين الفاعلين في المسرح العربي . ويتفق الدرمكي مع البدور في ضرورة تفعيل دور مندوبي الهيئة في العواصم العربية من أجل إبراز التجربة المسرحية العربية وإخراجها إلى العالم بشكل مناسب، لأن عدم تفعيل دور هؤلاء المندوبين قد يحوّل التجربة عن مسارها الصحيح، ويربطها بشخوص ومبان خالية المضامين . ويذهب الناقد المسرحي يحيى الحاج إلى أن الهيئة قد أسهمت في إبراز التجربة المسرحية العربية من خلال الأعمال المتنوعة التي اطلع المسرحيون عليها ضمن الورش والتظاهرات المختلفة، كما لعب مندوبوها في العواصم العربية دوراً كبيراً في تفاعل مسرحييها وتطوير خبراتهم . ويرصد المسرحي غانم ناصر ملامح تطور الهيئة في السنوات الأخيرة من خلال بعض الأعمال التي عُرضت والحديث عنها ضمن بعض الفعاليات والتظاهرات التي نظمتها الهيئة في الخارج بالتنسيق مع مندوبيها، وقد أسهم ذلك في احتكاك صناع المسرح في الوطن العربي بعضهم ببعض، وانفتاحهم على العديد من التجارب المسرحية الرائدة . \n\nأفكار:\n- المحتوى الرئيسي: الهيئة العربية للمسرح وأنشطتها\n- الثيمة الرئيسية: الثقافة والفنون\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 80%|████████  | 16/20 [01:25<00:21,  5.34s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nأصدر صندوق التنمية الثقافية في مصر، كتاباً يشرح الحياة المصرية في سيناء، ضمن سلسلة كتب سيصدرها الصندوق، عن الحياة المصرية في المحافظات الحدودية، وتقدم شرحاً تفصيلياً عن تراث كل محافظة وطبيعتها وأنماط الحياة فيها. الكتاب بعنوان «دليل التطريز السيناوي»، تأليف كمال عبد الله الحلو، وهذا الكتاب بداية سلسلة من الكتب تستهدف توثيق الحياة التراثية في المحافظات الحدودية، ويعكس زخم الحياة فيها، والفنون التي تميزت بها، وظهرت واضحة على تطريز ملابس أهلها، إعمالاً لمبدأ العدالة الثقافية، ومحاولة إظهار ما يميز كل محافظة من المحافظات من مفردات ثقافية وتراثية. ينقسم الكتاب إلى ثلاثة فصول، الأول منها يناقش «الوظيفة الاجتماعية للتطريز»، أما الفصل الثاني فيتناول الوحدات الزخرفية والعروق والحواجز، والفصل الثالث يحتوي على صور لبعض التصميمات التي تنتمي إلى الوحدات الزخرفية السيناوية، وتوظيفها على الملابس، والأشياء الخاصة بالديكور، والديكورات المنزلية. \n\nأفكار:\n- المحتوى الرئيسي: إصدار صندوق التنمية الثقافية في مصر لكتاب يشرح الحياة المصرية في سيناء\n- الثيمة الرئيسية: الثقافة والتراث\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالفئة المتوقعة'}]


 الثقافة

الفئة المتوقعة

 85%|████████▌ | 17/20 [01:31<00:16,  5.51s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nتحتل اللغة في النص الإبداعي مكانة جدّ مهمة، على اعتبار أنها العمود الفِقري فيه، بل إنه لا يمكن النظر إلى أي نص بمعزل عن اللغة التي تشكل لبناتِ عمارته، ولا يمكن لأية دراسة نقدية، إلا أن تولي هذه اللغة المزيد من العناية، ما دامت جزءاً رئيساً من جسد النص، تتفاعل مع العناصر المكونة له، مؤثرة فيها، ومتأثرة بها، على اعتبار أن اللغة الطيَعة على يدي كاتبها، تؤدي الوظيفة المتوخاة منها، من دون أن تقع في ربقة التكرار، سواء أكان ذلك بالنسبة إلى تجربة المبدع، أم بالنسبة إلى تجارب سواه .ولعلّ كتاباً كثيرين، تتوهج اللغة في نصوصهم، حيث تعطيها ألقاً وجمالية خاصين، إلى الدرجة التي نكاد فيها لا نتصور إنتاجاً إبداعياً، مائزاً، من دون لغة مائزة، وربما أن مقولة #187;النص عبارة عن عمارة لغوية#171;، تعد أقرب إلى الصواب، إذا وضعنا - نصب أعيننا - الأدواتِ الأخرى، في أي نص إبداعي، ومن بينها الرؤية والخيال، وعمق التجربة، وغيرها من الأدواتِ الخاصة بكل جنس إبداعي، على حدة .ويستطيع القارئ الفطن، النبيه، ذو التجربة الخاصة مع عملية القراءة، أن يميز لغة السارد، أو الشاعر، عن لغة سواهما، حتى وإن كان النص الذي يقدمه أحدهما، مغفلاً التوقيع، وهو ما تحدث عنه الكثير من النقاد والدارسين، وهم في حضرة إبداعات بعض الكتاب، المتفردين، ذوي البصمات الخاصة، غير المستنسخة مع غيرهم، ويبلغ الأمر أعلى مراتبه، هنا، في ما إذا كان المبدع المتناول، يحقق خاصية تجاوز لغة الذات، بين نص وآخر، بما يعني تطور لغته، وحيويتها، كي تنبض بالحياة، متجددة .ومن صفات الكاتب المتمكن، أنه يستطيع، لا سيما في مجال السرد، أن يحقق مسألة التدرج، أنى دعت الحاجة إلى ذلك، وليس أدلَ على هذا في النص القصصي، أو الروائي، من أن يتمكَن هذا الكاتب من تجسيد لغة شخوص متبايني المشارب الحياتية، والبيئية، والثقافية، وهو ليس بالأمر اليسير قط، لأن اعتماد مثل هذا التدرج اللغويّ، على صعيد النص الواحد، لابد أن يحقق ثنائية المواءمة والاختلاف، لئلا يكون ذلك على حساب تقنية هذا النص، وتماسك بنائه، ومنعه من الترهل . وبدهيّ، أنه لا يمكن للمبدع أن يحقق إيجاد لغته الخاصة، إلا عبر تشكيل معجم لغوي ذاتي، يستعين به، أثناء الكتابة، لتكون جزءاً من مختبره الإبداعي، ولتغدو اللبنة اللغوية جزءاً من نسيج هذا النص، وهو الشكل الأرقى، والأعلى، من التعامل مع الأداة اللغوية على الإطلاق، من دون أن يقع هذا المبدع، أثناء النهل من معجمه الخاص، في أوتوماتيكية التعامل اللغوي، هذه الأوتوماتيكية التي تجعل النص متخشباً، جافاً، بلاروح، وبلا حياة، وبالتالي، من دون أية قيمة جمالية، وإبداعية .وتأسيساً، على مثل هذا الكلام، فإن في خصيصة تعدد المستويات اللغوية لدى المبدع، وفي نصه، ما يثري هذا النص، ويسجل له مقاربته من الحياة، في شكل أدبي رفيع، بل إن التجسيد اللغوي لدى الناص، يغدو-في حد ذاته- ملمحاً بارزاً، في سياق النص، وثمة من يرى فيه بوابة المتلقي إلى النص والناص، بل ثمة من راح يبالغ، إلى درجة الجزم بأن اللغة تحدد طبيعة الإبداع، ومنزلته، ومستواه .elyousef@gmail.com \nالفئة المتوقعة: الدين\n\nمحتوى المقال:\nمحتوى المقال يتناول الحديث عن أهمية اللغة في النص الإبداعي، وكيف يمكن للغة أن تؤثر على النص وتجعله أكثر حيوية وجمالاً. كما يتحدث عن دور اللغة في تشكيل تجربة القارئ'}]


 الدين

محتوى المقال:
محتوى المقال يتناول الحديث عن أهمية اللغة في النص الإبداعي، وكيف يمكن للغة أن تؤثر على النص وتجعله أكثر حيوية وجمالاً. كما يتحدث عن دور اللغة في تشكيل تجربة القارئ

 90%|█████████ | 18/20 [01:36<00:10,  5.45s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nافتتح الشيخ الدكتور ماجد بن سعيد النعيمي رئيس الديوان الأميري في عجمان مساء أمس الأول الدورة الثانية لملتقى شاهندة للإبداع الروائي تحت عنوان سرديات الماء شرقا وغربا دورة المبدعين سلمى مطر وعلي الشدوي وذلك في جامعة العلوم والتكنولوجيا في عجمان.يأتي الملتقى على مدار يومين ليناقش جملة الدلالات والرموز التي شكلتها ثيمة الماء في مستويات عدة للسرد منها السرد الأدبي والتراثي والديني والفكري والحضاري بالإضافة إلى ثيمة الماء في الفن التشكيلي والسينمائي، وقد أقيمت في اليوم الأول للملتقى جلستان حيث دارت الأولى منها حول ثيمة الماء في الأدب والتشكيل أدارها القاص عبد الفتاح صبري وقدم فيها كل من د. سعيد بنكراد المغرب وإسلام بو شكير وطلال معلا سوريا أوراقاً بحثية حول الكيفية التي استخدمت فيها ثيمة الماء في نماذج روائية وتشكيلية.جاءت ورقة د. بنكراد تحت عنوان ذاكرة الماء ولا وعي السرد حيث تطرق إلى رمزية الماء وإحالاته الدلالية في السياق الثقافي الكوني حيث رأى أن تلك الرمزية تتمثل في ثلاث ثيمات وهي الخصوبة والتطهر والانبعاث متخذا من حكاية الطوفان الذي أغرق البشرية مستندا لدراسته الطوفان ليس فكرة، وليس مفهوماً يحيل إلى المجرد من العوالم، إنه على العكس من ذلك، مصدر لكل الحكايات الممكنة الخاصة بفكرة الانبعاث أو هو الشكل التشخيصي للحد المجرد كما يتحقق من خلال الرغبة الجماعية المولدة لكل ميل في تسريد التجربة وإدراجها ضمن الزمنية الإنسانية.وانتقل د. بنكراد من السياق الفكري إلى العياني متناولا نماذج روائية محددة ومن تلك النماذج روايتا أولاد حارتنا لنجيب محفوظ، والشراع والعاصفة لحنا مينة، حيث اعتبر أن المكان/الدهليز في رواية أولاد حارتنا والممثل في الحكاية الثانية من الرواية نفسها والتي تحمل عنوان جبل يعبر بشكل رمزي عن معنى الظلام في اتجاهين الأول له علاقة بالموت والآخر بالولادة ويرى د. بنكراد أن الماء الذي تم صبه فوق رؤوس الفتوات في الدهليز لا يمكن التعامل معه بشكل كمي وإنما بما يمثله في السياق العام للسرد من رموز ودلالات إن طشتا واحدا من الماء قد يكون كافيا لاستعادة صورة المياه الهادرة، إن الماء المسرد في الرواية ليس ماء عاديا، إنه يسقط من السماء على شكل شلال قد لا يؤدي إلى بلل رأس شخص أو شخصين، ولكنه دال، من باب التناظر، على غرق كلي، فليست الكمية هي المقصودة، بل الخزان الأسطوري كما تسلل إلى الذاكرة والوجدان هو الذي يسند الفعل السردي ويبرر آثاره أما في تناوله لرواية الشراع والعاصفة فقد تطرق إلى فكرة الشاطىء باعتباره المكان الذي يحدث فيه الفعل الحقيقي بتأثير من البحر حيث الصراع على امتلاك البحر هو الأساس في الرواية وهو محرك السرد.أما بو شكير فقدم ورقة تحت عنوان قراءة في الصراع بين الشراع والعاصفة لحنا مينة، مبررا اختياره لتلك الرواية بكونها نأت بنفسها عن الخوض في ثنائية البحر والصحراء التي وسمت برأيه معظم التجارب الروائية العربية، واعتبر بو شكير أن البحر لعب أدوارا مختلفة منها كونه فضاء للصراع شهد البحر في الرواية أحداثا مختلفة.منها ما وقع فيه، أي على سطحه وبين أمواجه، كمثل حادث غرق المنصورة مركب الطروسي، ومن الأحداث ما جرى عند شاطىء البحر، كالمعارك التي كان الطروسي يخوضها ضد أبي رشيد صاحب المواعين بالإضافة إلى كون البحر موضوعا للصراع، وطرفا فيه، حيث وجد أن عنوان الرواية نفسه يحيل إلى التناقض الشراع يحمل مدلولات إنسانية تحيل إلى قيم معينة كالحياة والحرية والانطلاق والحلم والغربة.. أما العاصفة فتحيل إلى قيم أخرى كالقوة والدمار والموت والخديعة.أما معلا فتناول في ورقته الماء والتشكيل الإماراتي مستعينا بعرض الكثير من النماذج للوحات فنانين إماراتيين ومنهم عبد القادر الريس ود. نجاة مكي وجويرية الخاجة وحسن شريف وغيرهم ليوضح الاختلافات في استخدام ثيمة الماء في أعمالهم معتبرا أن الماء واحد من المواضيع التي شغلت الفنانين في الإمارات منذ تأسيس المحترف الإماراتي، ومحاولتهم إغناء الذاكرة الجمالية والانفعال بالمرئيات التي يشكل البحر أهم سماتها وقد رأى معلا أن الجيل الأول من الفنانين عبر عن نظرة الخوف من البحر وقد تمثلت تلك الحالة في الأعمال التي صورت السفن المغادرة بكل ما تحمله من علامات القلق على مصير المسافر، ثم ظهر جيل آخر تعامل بعضه مع البحر بنظرة واقعية رومانسية، كما أشار معلا إلى أن شكل الموجة هو سمة الواجهة المعمارية الإماراتية. \nأفكار:\n- المحتوى الرئيسي: ملتقى شاهندة للإبداع الروائي\n- الثيمة الرئيسية: الأدب والثقافة\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

 95%|█████████▌| 19/20 [01:41<00:05,  5.27s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nنظمت رابطة اديبات الامارات لقاء تعريفياً للأصوات الجديدة لعرض تجربتهن وانتاجهن الإبداعي يوم الاثنين الماضي بحضور المستشار الثقافي للرابطة صالحة عبيد غابش ومنسقة البرامج ريم العيساوي وعدد من عضوات الرابطة والمبدعات.استهل اللقاء بتعريف كل مبدعة وتجربتها الإبداعية وتقديم بعض من انتاجها الأدبي من الشعر والقصة والخواطر. حيث قدمت الشاعرة موزة الشحي قصيدة بعنوان نفس مخملية تقول فيها: أيها الأفق الرائعاحضني في ظلال غيومكاحملني على كفوف خدودكودع دموعيتنهمر أمطاراًوالقت الشاعرة حورية أحمد قصيدة بعنوان الإعاقة ومن ابياتها:جيت اترجم معاني الاعاقة يا حضوري جيت أوضح مفاهيم تسكن الانسانجيت وشعري ممتزج في شعري جيت بعذوبة أفكار تحتضن أشجانوقدمت صالحة عبيد حسن طالبة في كلية التقنية العليا في الشارقة قصة قصيرة بعنوان زهايمر ومن أجوائها: كبرت ومازال شيء في داخلي ينتظر عودتها لتلعب معي. وأنا اسمع عن اخبارها بين الفينة والأخرى، التي تعود لتطفو على سطح الذكريات بصورة ضبابية مضمحلة من تعاف، الى هجرة، فزواج، فانفصال، لعودة.وقدمت بثينة عبدالكريم طالبة في مدرسة الظيت في رأس الخيمة خاطرة بعنوان تمر الأيام تقول فيها:تمر الأيام، تتلوها الشهور، ثم السنينتطوى فيها اعذب المشاعر واقسى الأحزاننتوه في دنيا تسيرنا تارة للأمام وتارة للخلف\n\nأفكار:\n- المحتوى الرئيسي: لقاء تعريفي للأصوات الجديدة في الأدب والشعر\n- الثيمة الرئيسية: الثقافة\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

100%|██████████| 20/20 [01:47<00:00,  5.36s/it]

[{'generated_text': '\nأنت نموذج لغوي مكلف بتصنيف مقالات الصحف العربية إلى واحدة من الفئات التحريرية المحددة مسبقًا، وذلك بالاعتماد فقط على الموضوع الرئيسي ومحتوى المقال. اقرأ كل مقال بعناية، ثم حدد فئة واحدة فقط من الفئات التالية تعكس بشكل أفضل الموضوع الأساسي للمقال: \n1. الثقافة\n2. المال \n3. الطب\n4. السياسة\n5. الدين\n6. الرياضة\n7. التكنولوجيا\n\nاتبع الخطوات التالية عند تحليل محتوى كل مقال:\n\nالخطوة 1: فهم المحتوى الأساسي\nاقرأ المقال بالكامل بعناية. حدد الحدث أو القضية أو الرسالة الرئيسية. قد يكون ذلك خبرًا أو تعليقًا أو تقريرًا يتعلق بمجالات مثل السياسة أو الصحة أو الاقتصاد أو الرياضة أو التكنولوجيا أو الثقافة.\n\nالخطوة 2: تحديد الموضوع السائد\nحدد الموضوع أو الفكرة الرئيسية. ركز على محتوى المقال والمفاهيم المتكررة فيه. تجاهل المواضيع الثانوية أو الجوانب الجانبية التي لا تُعبّر عن التركيز العام للمقال.\n\nالخطوة 3: مطابقة المقال مع فئة\nاختر الفئة الوحيدة التي تتوافق بشكل أفضل مع الموضوع السائد. كن دقيقًا: اختر الفئة الأكثر تحديدًا والأقرب صلة. لا تعتمد على الافتراضات أو المعرفة الخلفية خارج النص. إذا تناول المقال عدة مواضيع، اختر الموضوع الذي يتم التأكيد عليه أكثر أو الذي يُعتبر محوريًا لغرض المقال.\n\nالمثال 1\nمحتوى المقال:\nأكد الفنان عزت أبوعوف، رئيس مهرجان القاهرة السينمائي، إلغاء حفل ختام المهرجان الذي كان من المزمع أن يقام غداً، وذلك بسبب الظروف غير المستقرة التي تمر بها مصر حالياً.ونفى أبوعوف في تصريحات لـ"العربية.نت" سفر الضيوف الأجانب خوفاً مما تشهده مصر من مظاهرات، وما تردد عن أن هذا السفر قد تسبب في عدم إمكانية إقامة حفل الختام، مؤكداً أن وزير الثقافة دكتور محمد صابر عرب هو من أصدر قرار الإلغاء.وعن توزيع الجوائز التي كان من المزمع أن يتم في حفل الختام، شرح أنه سيقام مؤتمر صحافي سيكون بديلاً عن الحفل وسيتم من خلاله إعلان توزيع الجوائز والأفلام الفائزة في هذه الدورة.يُذكر أن حفل افتتاح المهرجان أيضاً تم في هدوء وبعيداً عن الصخب المعتاد، وذلك أيضاً بسبب الظروف نفسها التي تشهدها مصر.\n\nأفكار:\n- المحتوى الرئيسي: إلغاء حفل ختام مهرجان القاهرة السينمائي\n- الثيمة الرئيسية: الأنشطة الثقافية والفنية\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة\n\nالمثال 2\nمحتوى المقال:\nقال الرئيس التنفيذي للشركة السعودية للكهرباء زياد الشيحة، في مقابلة عبر الهاتف مع قناة "العربية"، إنه لأول مرة في تاريخ الشركة تراجع استهلاك المملكة في فترات الذروة. وأضاف الشيحة أن التراجع الذي حدث في استهلاك المملكة في 2016، مقارنة مع عام 2015، دفع الشركة لمراجعة السعات المطلوبة لدى دراسة المشاريع الجديدة. وأكد أن مسألة انخفاض الحمل الذروي لأول مرة في تاريخ الشركة عن العام جلعنا نراجع المحطات المستقبلية والتي ستكون بعقود شراء الطاقة، وهذا سيكون لمشاربع الإنتاج وتتم مراجعة السعات المطلوبة خاصة مع قلة الحمل الذروي في 2016. وستزود الشركة السعودية للكهرباء شركة زين السعودية بشبكة الألياف البصرية الممتدة لـ 60 ألف كم. وأوضح الشيحة أن "قطاع التوليد سيطرح للخصخصة كما هو معلن، ونعمل على الموضوع بشكل متوازن وشبه يومي". وكانت خسائر شركة السعودية للكهرباء قد تفاقمت بأكثر من 60%، في الربع الأخير من العام الماضي، مقارنة بالربع المماثل من عام 2015، لتبلغ 2.34 مليار ريال. من ناحية أخرى، ارتفعت أرباح الشركة بنسبة 37%، خلال العام الماضي، مقارنةً بعام 2015، لتبلغ 2.1 مليار ريال. وأرجعت الشركة تفاقم الخسائر الفصلية إلى ارتفاع تكلفة المبيعات نتيجة الزيادة في أسعار الوقود وارتفاع المصاريف التشغيلية.\n\nأفكار:\n- المحتوى الرئيسي: مقابلة مع زياد الشيحة، الرئيس التنفيذي للشركة السعودية للكهرباء\n- الثيمة الرئيسية: الاقتصاد والطاقة\n- الفئة الأنسب: المال والأعمال\n\nالفئة المتوقعة: المال\n\n\nالمثال 3\nمحتوى المقال:\nيعتقد بعض المدخنين أن السجائر الإلكترونية تعد أحد أهم العوامل المساعدة في الإقلاع عن التدخين، في حين يعتقد البعض الآخر أنها تعتبر وسيلة إغواء للاستمرار في الخضوع لتلك العادة المدمرة، إلا أن الأبحاث الطبية الحديثة تشير إلى أن الأخطار والفوائد لتلك النوعية من السجائر لاتزال غير معلومة بصورة واضحة بين المدخنين، وذلك وفق ما نشرت وكالة أنباء الشرق الأوسط المصرية. وكانت مجموعة من الباحثين قد أجرت أبحاثها على أكثر من 64 مدخنا، ولم ينجحوا في تحقيق إجماع حول الفوائد والأضرار المحتملة للسجائر الإلكترونية، وهو ما قد يعكس انقساما في المجتمع الطبي حول مدى ملاءمة تعزيز السجائر الإلكترونية كبديل أكثر أمنا للتدخين. وأوضح الباحثون أن معظم المشاركين في الدراسة يرون أن التدخين يعتبر شكلا من الإدمان، حيث تلعب الإرادة دورا قويا في الإقلاع عن هذه العادة المدمرة، في الوقت الذى حاول فيه جميع المشاركين في الدراسة مرة واحدة على الأقل الإقلاع عن العادة المدمرة.\n\nأفكار:\n- المحتوى الرئيسي: السجائر الإلكترونية ودورها في الإقلاع عن التدخين\n- الثيمة الرئيسية: الصحة والطب\n- الفئة الأنسب: الطب\n\nالفئة المتوقعة: الطب\n\n\nالمثال 4\nمحتوى المقال:\nأعرب المتحدث باسم الهيئة العليا للمفاوضات السورية سالم المسلط عن أمله في أن تنتقل روسيا فعليا لتقف إلى جانب الشعب السوري بدلا من النظام، وذلك عقب قراره بسحب القوات الروسية من سوريا. وأضاف المسلط أن هناك جدية لمست مؤخرا حيال المواقف الروسية للدفع نحو الحل السياسي للأزمة في سوريا، خلال جولة المحادثات الجديدة التي انطلقت في جنيف. هذا وأعلن متحدث باسم الرئيس الروسي فلاديمير بوتين بوتين بأن روسيا أبلغت الأسد بقرار سحب الجزء الرئيسي من القوات الروسية من سوريا. وقال المتحدث إن بوتين خلال اجتماعه بوزير دفاعه أمر اعتبارا من اليوم (الثلاثاء) ببدء سحب الجزء الرئيسي من القوات الروسية. في حين قال متحدث باسم بوتين إن القاعدة البحرية والجوية الروسية في سوريا تستمر في العمل كما في السابق. ووفقا للكرملين فإن بوتين طلب من وزير خارجيته سيرغي لافروف تكثيف الدور الروسي في عملية السلام في سوريا، مشيرا إلى ان  القوات الروسية في سوريا أوجدت ظروفا ملائمة لعملية السلام.\n\nأفكار:\n- المحتوى الرئيسي: تصريحات سالم المسلط، المتحدث باسم الهيئة العليا للمفاوضات السورية\n- الثيمة الرئيسية: السياسة والعلاقات الدولية\n- الفئة الأنسب: السياسة\n\nالفئة المتوقعة: السياسة\n\n\nالمثال 5\nمحتوى المقال:\nأكد عبداللطيف بخاري، رئيس لجنة الخبراء باتحاد القدم السعودي أن اتحاده يبحث عن 15 منصباً في اللجان الآسيوية، وأن هناك لجنة برئاسة خالد المرزوقي، عضو مجلس إدارة الاتحاد مكلفة بالاختيار. وقال بخاري لـ"في المرمى":" الترشيحات تتم بناء على معايير قارية، ونحن نبحث عن 15 منصباً في لجان الاتحاد الآسيوي". وبين بخاري أن لجنة المسابقات اقترحت إيجاد مراقب لكل مباراة، وزاد:" تقارير المراقب لن تغني عن تقارير الحكم، أما بالنسبة لتقارير الأول فيمكن للجنة الانضباط الاستناد عليها".\n\nأفكار:\n- المحتوى الرئيسي: تصريحات عبداللطيف بخاري، رئيس لجنة الخبراء في اتحاد القدم السعودي\n- الثيمة الرئيسية: الرياضة\n- الفئة الأنسب: الرياضة\n\nالفئة المتوقعة: الرياضة\n\n\nالمثال 6\nمحتوى المقال:\nيبدو أن هاتف #آيفون7  الجديد الذي ستصدره شركة آبل، لن يحمل الكثير من التغيرات، بحسب ما أفاد تقرير لـ "وول ستريت جورنول". فالهاتف الجديد سيأتي شبيها بالنسخة الحالية (آيفون6)، مع تغيير جذري على صعيد "الصوت" والسماعات. وحسب تقرير الصحيفة قد تزيل شركة #آبل منفذ سماعة الصوت، لتدمجه بالمنفذ الذي يوضع فيه شاحن الهاتف في الأسفل. وتراهن آبل من خلال إزالة المنفذ على جعل هاتفها الجديد "أرفع"، ومضاد للماء فإزالة فتحة السماعة، ستمنع تسرب الماء إلى الجهاز عبر الثقب، وتعطيله. ومن شأن إزالة المنفذ الذي يصل قطره إلى 2.5 ميلليمتر أن ينعكس إيجابا أيضاً على البطارية، على اعتبار أن التغيير سيفسح مساحة جديدة يمكن استغلالها. إلا أن التقرير لم يفصل كيف يمكن لمنفذ الشحن الجديد أن يمنع بدوره تسرب الماء إلى داخل الهاتف. في المقابل، يرى بعض منتقدي الشكل الجديد أو التغيير المنتظر أن الاستغناء عن السماعات التقليدية، سيجبر المستخدمين على شراء السماعات الأغلى التي تعمل بتقنية "بلوتوث".\n\nأفكار:\n- المحتوى الرئيسي: تقريرًا حول هاتف آيفون 7 الجديد من شركة آبل\n- الثيمة الرئيسية: التكنولوجيا\n- الفئة الأنسب: التكنولوجيا\n\nالفئة المتوقعة: التكنولوجيا\n\n\nالمثال 7\nمحتوى المقال:\n} قال رسول الله صلى الله عليه وسلم: «من أتى فراشه وهو ينوي أن يقوم يصلي من الليل فغلبته عينه حتى أصبح، كتب له ما نوى، وكان نومه صدقة عليه من ربه».} وقال صلى الله عليه وسلم: «ما تشاور قومإلا هداهم الله لأرشد أمورهم».\n\nأفكار:\n- المحتوى الرئيسي: الأحاديث المذكورة هي من أقوال النبي محمد صلى الله عليه وسلم\n- الثيمة الرئيسية: الدين والعقيدة\n- الفئة الأنسب: الدين\n\nالفئة المتوقعة: الدين\n\n\n Article Content: \nالشارقة - "الخليج":نظم مركز الشارقة للشعر الشعبي في مجلس ضاحية واسط مساء أمس الأول، أمسية شعرية احتفالية تكريمية للشيخة عائشة بنت محمد القاسمي احتفاء وتقديراً لدورها الكبير وإنجازاتها الخالدة في قطاع التعليم والمجتمع ودعمها الدائم للمرأة والطفل .جاءت الأمسية بعنوان "أميرة العلم" وشهدت حضور نخبة مميزة من المثقفات والأديبات وسيدات المجتمع والتربويات اللواتي عاصرن الشيخة عائشة إبان عملها في الحقل التربوي .قدمت للأمسية الشاعرة مريم النقبي التي رحبت بالحضور وعبرت من خلال المقدمة عن المكانة الكبيرة التي تحظى بها الشيخة عائشة في نفوس أبناء وبنات الشارقة، وقالت إن هذه الامسية جاءت تعبيراً عن حب وتقدير شرائح كبيرة من المجتمع لشخصها وماقدمته من جهد متواصل وعمل دؤوب خلال فترة عملها في قطاع التربية والتعليم .وألقت عريفة الحفل قصيدة مهداة منها للشيخة عائشة ومن القصيدة:"لِك من البصمات ما يكفي ويسد لو يمر الوقت ما حدٍ نساكفي المدارس كم بذلتي من جهد تشهد الاجيال ع كثرة عطاكانتي ساس العلم وانتي له عَمَد وانتي اللي ما حدٍ سوّى شراكتعشقين العلم من يوم المهد في دروب الخير تتباشر خطاكولو كتبنا أشعارنا عد ومدد ما وفينا . . ولا وصلنا مستواك"ثم ألقت الشاعرة صالحة غابش المستشارة الثقافية في المجلس الأعلى لشؤون الاسرة الكلمة الأولى في الأمسية، وعبرت فيها عن مشاعر التقدير والاعتزاز التي تكنها للشيخة عائشة وعن بدايات سموها مع التربية والتعليم وانجازاتها المتلاحقة في الميدان التربوي، وكشفت للحضور عن تفاصيل خاصة وجوانب جديدة من شخصية الشيخة لم تكن معروفة من قبل، فقالت إنها مخرجة مسرحية متمكنة اخرجت العديد من الأوبريتات واللوحات الفنية الإبداعية بالإضافة إلى أنها تكتب الشعر بين فينة وأخرى .بعد ذلك تم عرض فيلم تناول مسيرتها وسيرتها الإبداعية والذاتية بصورة فنية جميلة، ثم قدمت طالبات مدرسة اشبيلية لوحة استعراضية إنشاديه لقصيدة أميرة العلم التي صاغ كلماتها الشاعر راشد شرار مدير مركز الشارقة للشعبي وفيها : اهلا وْسهلا ببنت محمد السامي لي نورها عند جَيّتها تقدمهافي كَفها كان حلو الورد متنامي زهور فخر ونمت باحلى مواسمهاياعايشه جَيّتك نبراس لإلهامي مواطن العزّ بانت لي معالمهاوبعدها قدمت الدكتورة عائشة السيار، وعائشة سيف نائبة رئيس مجلس الشارقة للتعليم كلمات من القلب مشاركة منهما في الاحتفالية للتعبير عن مشاعرهما في الاحتفاء بأميرة العلم .لتبدأ بعدها الامسية الشعرية التي شاركت فيها كل من الشاعرات صوغه، ومهرة بني ياس وغرشوب الفجر . وأهدت كل واحدة من الشاعرات قصيدة شعرية للشخصية المكرمة كتبت خصيصاً بهذه المناسبة، وقالت صوغه في ابياتها التي أهدتها للشيخة عائشة :القاسميه والندا قاسمها لونه وشكله تسمعه باحكاهاتهتف مواقفها فدا مبسمها راياتها تتبع ثمين اخطاهاالمجد عاشه حالفٍ يغنمها تشرق ضيا وابها المجد يتباهاوتغنت الشاعرة مهرة بني ياس في أبياتها التي أهدتها لأميرة العلم بمكارمها وعطاءاتها اللامحدودة ومن قصيدتها:نعم بنت القواسم طيبين الساس وام المكرمه والجود وبنت قروم له في المجد والتاريخ قوة باس مروه وعز هيبه . . فعل وعزوموقد جاءت مشاركة الشاعرة غرشوب الفجر مميزة الأداء ومؤثرة لما تتمتع به من صوت شجي قدمت من خلاله القصائد بفن الشلة التي تفاعل معه جمهور الحاضرات .وفي ختام الأمسية قدمت الشاعرة مريم النقبي درعاً وهدية تذكارية للشيخة عائشة بنت محمد القاسمي مقدمة من دائرة الثقافة والإعلام ومركز الشارقة للشعر الشعبي . \nأفكار:\n- المحتوى الرئيسي: أمسية شعرية تكريمية للشيخة عائشة بنت محمد القاسمي\n- الثيمة الرئيسية: الثقافة والفنون\n- الفئة الأنسب: الثقافة\n\nالفئة المتوقعة: الثقافة '}]


 الثقافة

In [ ]:
pred = []

max_length = tokenizer.model_max_length
for i in tqdm(range(len(data3))):
    prompt = data3.iloc[i]["prompt"]
    # prompt = prompt[:max_length]
    # result = pipe(prompt, pad_token_id=pipe.tokenizer.eos_token_id)
    result = pipe(prompt[:tokenizer.model_max_length], truncation=True, pad_token_id=pipe.tokenizer.eos_token_id)
    answer = result[0]['generated_text'].split("الفئة المتوقعة:")[-1].strip()

    pred.append(answer)

100%|██████████| 1000/1000 [1:28:14<00:00,  5.29s/it]

In [ ]:
pred_cot = pd.DataFrame()
pred_cot['Predicted'] = pred
pred_cot['Predicted'].value_counts()

Predicted
السياسة                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      132
الرياضة                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      112
التكنولوجيا                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  109
المال                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         86
الطب                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          83
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...

In [ ]:
nor_pre = []
for pr in pred_cot['Predicted']:
  if "الرياضة" in pr:
    nor_pre.append("Sports")
  elif "الصحة" in pr:
    nor_pre.append("Medical")
  elif "الطب" in pr:
    nor_pre.append("Medical")
  elif "الثقافة" in pr:
    nor_pre.append("Culture")
  elif "المال" in pr:
    nor_pre.append("Finance")
  elif "السياسة" in pr:
    nor_pre.append("Politics")
  elif "الدين" in pr:
    nor_pre.append("Religion")
  elif "التكنولوجيا" in pr:
    nor_pre.append("Tech")
  else:
    nor_pre.append("Unclassified")

In [ ]:
pred_cot['Normalized Prediction'] = nor_pre
pred_cot['Normalized Prediction'].value_counts()

Normalized Prediction
Politics        170
Tech            136
Sports          136
Religion        130
Medical         126
Finance         120
Unclassified     95
Culture          87
Name: count, dtype: int64

In [ ]:
pred_cot.to_csv('Allam CoT News Classification.xlsx', index = False)

In [ ]:
print(classification_report(y_true, pred_cot['Normalized Prediction'].values, digits = 4))

              precision    recall  f1-score   support

     Culture     0.9425    0.5467    0.6920       150
     Finance     0.8750    0.7000    0.7778       150
     Medical     0.9286    0.7800    0.8478       150
    Politics     0.7765    0.8800    0.8250       150
    Religion     0.6385    0.8300    0.7217       100
      Sports     0.9779    0.8867    0.9301       150
        Tech     0.8456    0.7667    0.8042       150
Unclassified     0.0000    0.0000    0.0000         0

    accuracy                         0.7670      1000
   macro avg     0.7481    0.6738    0.6998      1000
weighted avg     0.8658    0.7670    0.8037      1000